import { StyleSheet } from "react-native";
import { marketingPalette as C } from "../../shared/design/palette";
import { F } from "./fonts";

export const accountSettingsStyles = StyleSheet.create({
  settingsPage: {
    gap: 22,
  },
  settingsProfileCard: {
    gap: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    padding: 16,
  },
  settingsProfileIdentity: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  settingsAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.primaryGhost,
    borderWidth: 1,
    borderColor: C.line,
  },
  settingsProfileCopy: {
    minWidth: 0,
    flex: 1,
    gap: 3,
  },
  settingsProfileTitle: {
    color: C.text,
    fontSize: 17,
    fontFamily: F.extraBold,
  },
  settingsProfileSubtitle: {
    color: C.textSoft,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: F.regular,
  },
  settingsSection: {
    gap: 8,
  },
  settingsSectionLabel: {
    marginLeft: 4,
    color: C.textMuted,
    fontSize: 12,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    fontFamily: F.bold,
  },
  settingsGroup: {
    overflow: "hidden",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
  },
  settingsBlock: {
    gap: 12,
    padding: 16,
  },
  settingsKeyRow: {
    minHeight: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  settingsRowCopy: {
    minWidth: 0,
    flex: 1,
    gap: 3,
  },
  settingsRowTitle: {
    color: C.text,
    fontSize: 15,
    fontFamily: F.bold,
  },
  settingsRowValue: {
    maxWidth: "48%",
    color: C.textMuted,
    fontSize: 13,
    fontFamily: F.semibold,
  },
  settingsHelp: {
    color: C.textSoft,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: F.regular,
  },
  settingsInput: {
    minHeight: 46,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    color: C.text,
    paddingHorizontal: 13,
    fontSize: 15,
    fontFamily: F.semibold,
  },
  settingsButtonRow: {
    flexDirection: "row",
    gap: 10,
  },
  settingsButton: {
    minHeight: 44,
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  settingsButtonPrimary: {
    borderColor: C.primaryDeep,
    backgroundColor: C.primaryDeep,
  },
  settingsButtonSecondary: {
    borderColor: C.line,
    backgroundColor: C.white,
  },
  settingsButtonDanger: {
    borderColor: "#A83939",
    backgroundColor: "#A83939",
  },
  settingsButtonPrimaryText: {
    color: C.white,
    fontSize: 13,
    textAlign: "center",
    fontFamily: F.bold,
  },
  settingsButtonSecondaryText: {
    color: C.text,
    fontSize: 13,
    textAlign: "center",
    fontFamily: F.bold,
  },
  settingsDivider: {
    height: StyleSheet.hairlineWidth,
    marginLeft: 16,
    backgroundColor: C.line,
  },
  settingsToggleRow: {
    minHeight: 68,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  settingsLinkRow: {
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    paddingHorizontal: 16,
  },
  settingsRowPressed: {
    backgroundColor: C.primaryGhost,
  },
  settingsLinkMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  settingsChevron: {
    color: C.textMuted,
    fontSize: 24,
    lineHeight: 26,
    fontFamily: F.regular,
  },
  settingsDangerText: {
    color: "#A83939",
  },
  settingsDangerBlock: {
    gap: 12,
    padding: 16,
  },
  settingsMessage: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.primaryGhost,
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  settingsMessageText: {
    color: C.textSoft,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: F.semibold,
  },
  settingsSummaryBlock: {
    gap: 14,
    padding: 16,
  },
  settingsSummaryRow: {
    gap: 3,
  },
  settingsSummaryValue: {
    color: C.text,
    fontSize: 14,
    lineHeight: 19,
    fontFamily: F.semibold,
  },
  authPage: {
    gap: 24,
    paddingTop: 8,
  },
  authIntro: {
    gap: 7,
  },
  authTitle: {
    color: C.text,
    fontSize: 24,
    lineHeight: 30,
    fontFamily: F.extraBold,
  },
  authDescription: {
    color: C.textSoft,
    fontSize: 14,
    lineHeight: 20,
    fontFamily: F.regular,
  },
  authCard: {
    gap: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    padding: 16,
  },
  authSocialGroup: {
    gap: 10,
  },
  authAppleButton: {
    width: "100%",
    height: 48,
  },
  authGoogleButton: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    paddingHorizontal: 16,
  },
  authGoogleButtonPressed: {
    backgroundColor: C.primaryGhost,
  },
  authGoogleMark: {
    color: "#4285F4",
    fontSize: 18,
    fontFamily: F.extraBold,
  },
  authGoogleButtonText: {
    color: C.text,
    fontSize: 14,
    fontFamily: F.bold,
  },
  authSocialStatus: {
    color: C.textMuted,
    fontSize: 12,
    textAlign: "center",
    fontFamily: F.semibold,
  },
  authDividerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  authDividerLine: {
    height: StyleSheet.hairlineWidth,
    flex: 1,
    backgroundColor: C.line,
  },
  authDividerText: {
    color: C.textMuted,
    fontSize: 11,
    fontFamily: F.semibold,
  },
  authField: {
    gap: 7,
  },
  authFieldLabel: {
    color: C.text,
    fontSize: 13,
    fontFamily: F.bold,
  },
  authFinePrint: {
    color: C.textMuted,
    fontSize: 11,
    lineHeight: 16,
    textAlign: "center",
    fontFamily: F.regular,
  },
  authInlineButton: {
    minHeight: 44,
    alignSelf: "flex-end",
    alignItems: "center",
    justifyContent: "center",
    marginTop: -8,
    paddingHorizontal: 4,
  },
  authLegalRow: {
    minHeight: 28,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    marginTop: -12,
  },
  authLegalLink: {
    minHeight: 44,
    justifyContent: "center",
  },
  authLegalLinkText: {
    color: C.primaryDeep,
    fontSize: 11,
    lineHeight: 16,
    fontFamily: F.bold,
  },
  authSwitchRow: {
    alignItems: "center",
    gap: 4,
  },
  authSwitchCopy: {
    color: C.textSoft,
    fontSize: 13,
    fontFamily: F.regular,
  },
  authTextButton: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  authTextButtonLabel: {
    color: C.primaryDeep,
    fontSize: 14,
    fontFamily: F.bold,
  },
  personalizationPage: {
    gap: 16,
    paddingTop: 8,
  },
  flowHeroCard: {
    alignItems: "center",
    gap: 10,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    paddingHorizontal: 20,
    paddingVertical: 24,
  },
  flowHeroIcon: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.primaryGhost,
    borderWidth: 1,
    borderColor: C.line,
  },
  flowHeroIconText: {
    color: C.primaryDeep,
    fontSize: 24,
    fontFamily: F.extraBold,
  },
  surveyCard: {
    gap: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    padding: 16,
  },
  surveyQuestionHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  surveyNumber: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.primaryGhost,
    borderWidth: 1,
    borderColor: C.line,
  },
  surveyNumberText: {
    color: C.primaryDeep,
    fontSize: 12,
    fontFamily: F.extraBold,
  },
  surveyTitle: {
    color: C.text,
    fontSize: 16,
    lineHeight: 21,
    fontFamily: F.extraBold,
  },
  surveyChipWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  surveyChip: {
    minHeight: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  surveyChipSelected: {
    borderColor: C.primaryDeep,
    backgroundColor: C.primaryGhost,
  },
  surveyChipText: {
    color: C.textSoft,
    fontSize: 13,
    fontFamily: F.semibold,
  },
  surveyChipTextSelected: {
    color: C.primaryDeep,
    fontFamily: F.bold,
  },
  surveyOptionStack: {
    gap: 8,
  },
  surveyRadioRow: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    paddingHorizontal: 13,
  },
  surveyRadioRowSelected: {
    borderColor: C.primaryDeep,
    backgroundColor: C.primaryGhost,
  },
  surveyRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: C.textMuted,
    alignItems: "center",
    justifyContent: "center",
  },
  surveyRadioSelected: {
    borderColor: C.primaryDeep,
  },
  surveyRadioDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: C.primaryDeep,
  },
  surveyRadioLabel: {
    color: C.text,
    fontSize: 14,
    fontFamily: F.semibold,
  },
  personalizationActions: {
    gap: 4,
    paddingTop: 4,
  },
  personalizationSkipButton: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
  },
});
