import { StyleSheet } from "react-native";
import { marketingPalette as C } from "../../shared/design/palette";
import { F } from "./fonts";

export const appChromeStyles = StyleSheet.create({
  contextHeader: {
    borderBottomWidth: 1,
    borderBottomColor: C.line,
    backgroundColor: C.white,
  },
  contextHeaderInner: {
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  contextHeaderIdentity: {
    minWidth: 0,
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  contextBrandMark: {
    width: 34,
    height: 34,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.primaryGhost,
    alignItems: "center",
    justifyContent: "center",
  },
  contextBackButton: {
    width: 44,
    height: 44,
    marginLeft: -5,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  contextHeaderTitle: {
    flexShrink: 1,
    color: C.text,
    fontSize: 18,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  contextStatusPill: {
    maxWidth: "42%",
    minHeight: 28,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.primaryGhost,
    paddingHorizontal: 10,
  },
  contextStatusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: C.primaryDeep,
  },
  contextStatusText: {
    flexShrink: 1,
    color: C.primaryDeep,
    fontSize: 11,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  mapCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.line,
    overflow: "hidden",
    backgroundColor: C.white,
  },
  mapView: {
    width: "100%",
    height: 260,
  },
  storeActionRow: {
    marginTop: 6,
    alignSelf: "stretch",
    alignItems: "flex-start",
  },
  storeActionBtn: {
    minHeight: 34,
    minWidth: 108,
    borderRadius: 8,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
  },
  resultMeta: {
    color: C.textMuted,
    fontSize: 12,
    fontFamily: F.bold,
  },
  formInput: {
    height: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    color: C.text,
    paddingHorizontal: 12,
    fontSize: 14,
    fontFamily: F.semibold,
  },
  itemName: {
    color: C.text,
    fontSize: 16,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  itemMeta: {
    color: C.textSoft,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: F.regular,
  },
  storePrice: {
    color: C.primaryDeep,
    fontSize: 12,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  tagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 4,
  },
  tag: {
    borderRadius: 999,
    backgroundColor: C.primaryGhost,
    color: C.primaryDeep,
    fontSize: 12,
    fontWeight: "700",
    paddingHorizontal: 9,
    paddingVertical: 4,
    fontFamily: F.bold,
  },
  alertTitle: {
    color: C.text,
    fontSize: 15,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  alertTime: {
    color: C.textMuted,
    fontSize: 11,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  authBtn: {
    minHeight: 42,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  authBtnPrimary: {
    backgroundColor: C.primary,
    borderColor: C.primary,
  },
  authBtnDanger: {
    backgroundColor: "#A83939",
    borderColor: "#A83939",
  },
  authBtnSecondary: {
    backgroundColor: C.white,
    borderColor: C.line,
  },
  authBtnPrimaryText: {
    color: C.white,
    fontSize: 13,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  authBtnSecondaryText: {
    color: C.text,
    fontSize: 13,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  authBtnDangerText: {
    color: C.white,
    fontSize: 13,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  bottomBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingTop: 13,
    borderTopWidth: 1,
    borderTopColor: C.line,
    backgroundColor: C.white,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    shadowColor: "#071f12",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: -6 },
    elevation: 16,
    overflow: "visible",
  },
  tabRow: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: 60,
  },
  tabBtn: {
    flex: 1,
    minHeight: 58,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  tabBtnActive: {
    backgroundColor: C.primaryGhost,
  },
  tabBtnMain: {
    top: -20,
    flex: 0,
    width: 68,
    height: 68,
    minHeight: 68,
    borderRadius: 34,
    borderWidth: 4,
    borderColor: C.white,
    backgroundColor: C.primaryDeep,
    shadowColor: "#071f12",
    shadowOpacity: 0.14,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 8,
  },
  tabBtnMainActive: {
    backgroundColor: C.primaryDeep,
  },
  tabBtnContent: {
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    gap: 2,
  },
  tabBtnMainContent: {
    transform: [{ translateY: 1 }],
  },
  tabLabel: {
    color: C.textMuted,
    fontSize: 9,
    lineHeight: 12,
    fontWeight: "800",
    fontFamily: F.extraBold,
    textAlign: "center",
  },
  tabLabelActive: {
    color: C.primaryDeep,
  },
  tabLabelMain: {
    color: C.white,
  },
  bottomAlertBadge: {
    position: "absolute",
    top: -9,
    right: -12,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 4,
    backgroundColor: "#EF4444",
    borderWidth: 2,
    borderColor: C.white,
    alignItems: "center",
    justifyContent: "center",
  },
  bottomAlertBadgeText: {
    color: C.white,
    fontSize: 9,
    lineHeight: 11,
    fontFamily: F.extraBold,
  },
});
