import { StyleSheet } from "react-native";
import { marketingPalette as C } from "../../shared/design/palette";
import { F } from "./fonts";

export const appChromeStyles = StyleSheet.create({
  mapCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.line,
    overflow: "hidden",
    backgroundColor: C.white,
  },
  mapView: {
    width: "100%",
    height: 260,
  },
  storeActionRow: {
    marginTop: 6,
    alignSelf: "stretch",
    alignItems: "flex-start",
  },
  storeActionBtn: {
    minHeight: 34,
    minWidth: 108,
    borderRadius: 8,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
  },
  resultMeta: {
    color: C.textMuted,
    fontSize: 12,
    fontFamily: F.bold,
  },
  formInput: {
    height: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    color: C.text,
    paddingHorizontal: 12,
    fontSize: 14,
    fontFamily: F.semibold,
  },
  itemName: {
    color: C.text,
    fontSize: 16,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  itemMeta: {
    color: C.textSoft,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: F.regular,
  },
  storePrice: {
    color: C.primaryDeep,
    fontSize: 12,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  tagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 4,
  },
  tag: {
    borderRadius: 999,
    backgroundColor: C.primaryGhost,
    color: C.primaryDeep,
    fontSize: 12,
    fontWeight: "700",
    paddingHorizontal: 9,
    paddingVertical: 4,
    fontFamily: F.bold,
  },
  alertTitle: {
    color: C.text,
    fontSize: 15,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  alertTime: {
    color: C.textMuted,
    fontSize: 11,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  authActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  legalLinkRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 6,
  },
  legalActionBtn: {
    minWidth: 116,
  },
  permissionGroup: {
    gap: 8,
    marginTop: 8,
  },
  permissionGroupTitle: {
    color: C.text,
    fontSize: 13,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  permissionActionBtn: {
    minWidth: 132,
  },
  authModeRow: {
    flexDirection: "row",
    gap: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    padding: 4,
  },
  authModeBtn: {
    flex: 1,
    minHeight: 36,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
  },
  authModeBtnActive: {
    backgroundColor: C.primary,
  },
  authModeText: {
    color: C.textMuted,
    fontSize: 12,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  authModeTextActive: {
    color: C.white,
  },
  authBtn: {
    minHeight: 42,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  authBtnPrimary: {
    backgroundColor: C.primary,
    borderColor: C.primary,
  },
  authBtnDanger: {
    backgroundColor: "#A83939",
    borderColor: "#A83939",
  },
  authBtnSecondary: {
    backgroundColor: C.white,
    borderColor: C.line,
  },
  authBtnPrimaryText: {
    color: C.white,
    fontSize: 13,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  authBtnSecondaryText: {
    color: C.text,
    fontSize: 13,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  authBtnDangerText: {
    color: C.white,
    fontSize: 13,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  destructiveWarning: {
    color: "#A83939",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  bottomBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: C.line,
    backgroundColor: C.white,
  },
  tabRow: {
    flexDirection: "row",
    gap: 8,
  },
  tabBtn: {
    flex: 1,
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  tabBtnActive: {
    backgroundColor: C.primary,
    borderColor: C.primary,
  },
  tabBtnContent: {
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
  },
  tabIcon: {
    fontSize: 14,
  },
  tabText: {
    color: C.textMuted,
    fontSize: 11,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  tabTextActive: {
    color: C.white,
    fontFamily: F.bold,
  },
  toastWrap: {
    position: "absolute",
    zIndex: 20,
    minHeight: 46,
    borderRadius: 999,
    backgroundColor: C.text,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    shadowColor: "#000",
    shadowOpacity: 0.16,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  toastText: {
    color: C.white,
    fontSize: 13,
    fontWeight: "800",
    fontFamily: F.extraBold,
    textAlign: "center",
  },

});
