import { StyleSheet } from "react-native";
import { marketingPalette as C } from "../../shared/design/palette";
import { F } from "./fonts";

export const appChromeStyles = StyleSheet.create({
  contextHeader: {
    backgroundColor: C.white,
    paddingBottom: 8,
  },
  contextHeaderInner: {
    minHeight: 62,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  contextHeaderIdentity: {
    minWidth: 0,
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  contextBackButton: {
    width: 40,
    height: 44,
    marginLeft: -8,
    alignItems: "center",
    justifyContent: "center",
  },
  contextHeaderTitle: {
    flexShrink: 1,
    color: C.text,
    fontSize: 22,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  contextHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  mapCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.line,
    overflow: "hidden",
    backgroundColor: C.white,
  },
  mapView: {
    width: "100%",
    height: 260,
  },
  storeActionRow: {
    marginTop: 6,
    alignSelf: "stretch",
    alignItems: "flex-start",
  },
  storeActionBtn: {
    minHeight: 34,
    minWidth: 108,
    borderRadius: 8,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
  },
  resultMeta: {
    color: C.textMuted,
    fontSize: 12,
    fontFamily: F.bold,
  },
  formInput: {
    height: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    color: C.text,
    paddingHorizontal: 12,
    fontSize: 14,
    fontFamily: F.semibold,
  },
  itemName: {
    color: C.text,
    fontSize: 16,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  itemMeta: {
    color: C.textSoft,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: F.regular,
  },
  storePrice: {
    color: C.primaryDeep,
    fontSize: 12,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  tagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 4,
  },
  tag: {
    borderRadius: 999,
    backgroundColor: C.primaryGhost,
    color: C.primaryDeep,
    fontSize: 12,
    fontWeight: "700",
    paddingHorizontal: 9,
    paddingVertical: 4,
    fontFamily: F.bold,
  },
  authBtn: {
    minHeight: 42,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  authBtnPrimary: {
    backgroundColor: C.primary,
    borderColor: C.primary,
  },
  authBtnDanger: {
    backgroundColor: "#A83939",
    borderColor: "#A83939",
  },
  authBtnSecondary: {
    backgroundColor: C.white,
    borderColor: C.line,
  },
  authBtnPrimaryText: {
    color: C.white,
    fontSize: 13,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  authBtnSecondaryText: {
    color: C.text,
    fontSize: 13,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  authBtnDangerText: {
    color: C.white,
    fontSize: 13,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  bottomBar: {
    position: "absolute",
    zIndex: 20,
    minHeight: 72,
    padding: 6,
    borderWidth: 1,
    borderColor: "#E7ECE9",
    backgroundColor: C.white,
    borderRadius: 36,
    shadowColor: "#071f12",
    shadowOpacity: 0.14,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 8 },
    elevation: 18,
    overflow: "visible",
  },
  tabRow: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: 58,
    gap: 2,
  },
  tabBtn: {
    flex: 1,
    minWidth: 0,
    minHeight: 58,
    borderRadius: 29,
    alignItems: "center",
    justifyContent: "center",
  },
  tabBtnActive: {
    backgroundColor: "#EEF1EF",
  },
  tabBtnContent: {
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    gap: 3,
  },
  tabLabel: {
    color: C.textMuted,
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "800",
    fontFamily: F.extraBold,
    textAlign: "center",
  },
  tabLabelActive: {
    color: C.primaryDeep,
  },
  bottomAlertBadge: {
    position: "absolute",
    top: -9,
    right: -12,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 4,
    backgroundColor: "#EF4444",
    borderWidth: 2,
    borderColor: C.white,
    alignItems: "center",
    justifyContent: "center",
  },
  bottomAlertBadgeText: {
    color: C.white,
    fontSize: 9,
    lineHeight: 11,
    fontFamily: F.extraBold,
  },
});
