import { StyleSheet } from "react-native";
import { marketingPalette as C } from "../../shared/design/palette";
import { F } from "./fonts";

export const catalogStyles = StyleSheet.create({
  dealSectionCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    padding: 12,
    gap: 10,
    marginTop: 2,
  },
  dealFeedList: {
    gap: 8,
  },
  dealFeedGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  dealFeedItem: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    padding: 10,
    gap: 10,
    flexDirection: "row",
    alignItems: "stretch",
  },
  dealFeedItemActive: {
    borderColor: C.primary,
    backgroundColor: C.primaryGhost,
  },
  dealFeedThumb: {
    width: 74,
    height: 74,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
  },
  dealFeedThumbPlaceholder: {
    width: 74,
    height: 74,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.primaryGhost,
    alignItems: "center",
    justifyContent: "center",
  },
  dealFeedMain: {
    flex: 1,
    gap: 3,
  },
  dealFeedAction: {
    justifyContent: "flex-end",
    minWidth: 66,
    alignItems: "center",
  },
  dealSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  inlinePill: {
    minHeight: 44,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: C.primary,
    backgroundColor: C.primaryGhost,
    alignItems: "center",
    justifyContent: "center",
  },
  inlinePillDisabled: {
    borderColor: C.line,
    backgroundColor: C.bg,
  },
  inlinePillText: {
    color: C.primaryDeep,
    fontSize: 11,
    fontWeight: "800",
    fontFamily: F.bold,
  },
  inlinePillTextDisabled: {
    color: C.textMuted,
  },
  dealSectionScroll: {
    gap: 10,
    paddingRight: 6,
  },
  homeProductList: {
    gap: 0,
  },
  homeResultsRow: {
    minHeight: 28,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  homeProductRow: {
    minHeight: 126,
    borderBottomWidth: 1,
    borderBottomColor: C.line,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  homeProductThumb: {
    width: 88,
    height: 88,
    borderRadius: 12,
    backgroundColor: C.primaryPale,
  },
  homeProductThumbPlaceholder: {
    width: 88,
    height: 88,
    borderRadius: 12,
    backgroundColor: C.primaryPale,
    alignItems: "center",
    justifyContent: "center",
  },
  homeProductMain: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  homeProductTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
  },
  homeProductName: {
    flex: 1,
    minWidth: 0,
    lineHeight: 20,
  },
  homeDealInline: {
    borderRadius: 5,
    overflow: "hidden",
    backgroundColor: C.primaryGhost,
    color: C.primaryDeep,
    paddingHorizontal: 5,
    fontSize: 10,
    lineHeight: 16,
    fontWeight: "900",
    fontFamily: F.extraBold,
  },
  homeFavoriteTag: {
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: C.primaryGhost,
    color: C.primaryDeep,
    paddingHorizontal: 7,
    paddingVertical: 3,
    fontSize: 10,
    fontWeight: "900",
    fontFamily: F.extraBold,
  },
  homeStoreLine: {
    color: C.primaryDeep,
    fontSize: 12,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  homeTrendLine: {
    marginTop: 2,
    flexShrink: 1,
  },
  homeDeltaText: {
    fontSize: 12,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  homeDeltaDown: { color: "#2563EB" },
  homeDeltaFlat: { color: C.textMuted },
  homeDeltaUp: { color: "#C2413B" },
  homeProductPriceCol: {
    width: 96,
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 8,
  },
  homeListBtn: {
    minHeight: 30,
    borderRadius: 8,
    backgroundColor: C.primaryGhost,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 9,
  },
  homeListBtnActive: {
    backgroundColor: C.primaryPale,
  },
  homeListBtnText: {
    color: C.primaryDeep,
    fontSize: 11,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  homeListBtnTextActive: {
    color: C.text,
  },
  dealCard: {
    width: "48.5%",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    overflow: "hidden",
  },
  dealCardActive: {
    borderColor: C.primary,
  },
  dealCardImage: {
    width: "100%",
    height: 112,
    backgroundColor: C.primaryPale,
  },
  dealCardImagePlaceholder: {
    width: "100%",
    height: 112,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.primaryPale,
  },
  dealCardBody: {
    padding: 10,
    gap: 4,
  },
  dealCardBottomRow: {
    marginTop: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  dealPrice: {
    color: C.text,
    fontSize: 20,
    fontWeight: "900",
    fontFamily: F.extraBold,
  },
});
