import { StyleSheet } from "react-native";
import { marketingPalette as C, semanticPalette } from "../../shared/design/palette";
import { F } from "./fonts";

export const catalogStyles = StyleSheet.create({
  inlinePill: {
    minHeight: 44,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: C.primary,
    backgroundColor: C.primaryGhost,
    alignItems: "center",
    justifyContent: "center",
  },
  inlinePillText: {
    color: C.primaryDeep,
    fontSize: 11,
    fontWeight: "800",
    fontFamily: F.bold,
  },
  homeProductList: {
    gap: 0,
  },
  homeFeedFooter: { minHeight: 48, paddingVertical: 16, alignItems: "center", justifyContent: "center" },
  homeResultsRow: {
    minHeight: 28,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  homeProductRow: {
    borderBottomWidth: 1,
    borderBottomColor: C.line,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  homeProductThumb: {
    width: 88,
    height: 88,
    borderRadius: 12,
    backgroundColor: C.white,
  },
  homeProductThumbPlaceholder: {
    width: 88,
    height: 88,
    borderRadius: 12,
    backgroundColor: C.white,
    alignItems: "center",
    justifyContent: "center",
  },
  homeProductThumbCompact: { height: 68 },
  homeProductMain: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  homeProductTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
  },
  homeProductName: {
    flex: 1,
    minWidth: 0,
    lineHeight: 20,
  },
  homeDealInline: {
    borderRadius: 5,
    overflow: "hidden",
    backgroundColor: C.primaryGhost,
    color: C.primaryDeep,
    paddingHorizontal: 5,
    fontSize: 10,
    lineHeight: 16,
    fontWeight: "900",
    fontFamily: F.extraBold,
  },
  homeFavoriteTag: {
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: C.primaryGhost,
    color: C.primaryDeep,
    paddingHorizontal: 7,
    paddingVertical: 3,
    fontSize: 10,
    fontWeight: "900",
    fontFamily: F.extraBold,
  },
  homeStoreLine: {
    color: C.primaryDeep,
    fontSize: 12,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  homeTrendLine: {
    marginTop: 2,
    flexShrink: 1,
  },
  homeDeltaText: {
    fontSize: 12,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  homeDeltaDown: { color: C.primaryDeep },
  homeDeltaFlat: { color: C.textMuted },
  homeDeltaUp: { color: semanticPalette.priceIncrease },
  homeProductPriceCol: {
    width: 96,
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 8,
  },
  homeListBtn: {
    minHeight: 30,
    borderRadius: 8,
    backgroundColor: C.primaryGhost,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 9,
  },
  homeListBtnActive: {
    backgroundColor: C.primaryPale,
  },
  homeListBtnText: {
    color: C.primaryDeep,
    fontSize: 11,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  homeListBtnTextActive: {
    color: C.text,
  },
  dealPrice: {
    color: C.text,
    fontSize: 20,
    fontWeight: "900",
    fontFamily: F.extraBold,
  },
});
