import { StyleSheet } from "react-native";
import { marketingPalette as C } from "../../shared/design/palette";
import { F } from "./fonts";

export const catalogStyles = StyleSheet.create({
  dealSectionCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    padding: 12,
    gap: 10,
    marginTop: 2,
  },
  dealFeedList: {
    gap: 8,
  },
  dealFeedGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  dealFeedItem: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    padding: 10,
    gap: 10,
    flexDirection: "row",
    alignItems: "stretch",
  },
  dealFeedItemActive: {
    borderColor: C.primary,
    backgroundColor: C.primaryGhost,
  },
  dealFeedThumb: {
    width: 74,
    height: 74,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
  },
  dealFeedThumbPlaceholder: {
    width: 74,
    height: 74,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.primaryGhost,
    alignItems: "center",
    justifyContent: "center",
  },
  dealFeedMain: {
    flex: 1,
    gap: 3,
  },
  dealFeedAction: {
    justifyContent: "flex-end",
    minWidth: 66,
    alignItems: "center",
  },
  dealSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  inlinePill: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: C.primary,
    backgroundColor: C.primaryGhost,
  },
  sortPill: {
    borderColor: C.line,
    backgroundColor: C.white,
  },
  sortPillActive: {
    borderColor: C.primary,
    backgroundColor: C.primaryGhost,
  },
  sortPillTextActive: {
    color: C.primaryDeep,
  },
  inlinePillDisabled: {
    borderColor: C.line,
    backgroundColor: C.bg,
  },
  inlinePillText: {
    color: C.primaryDeep,
    fontSize: 11,
    fontWeight: "800",
    fontFamily: F.bold,
  },
  inlinePillTextDisabled: {
    color: C.textMuted,
  },
  sortOptionsWrap: {
    flexDirection: "row",
    gap: 8,
  },
  dealSectionScroll: {
    gap: 10,
    paddingRight: 6,
  },
  homeProductList: {
    gap: 8,
  },
  homeResultsRow: {
    minHeight: 28,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  homeProductRow: {
    minHeight: 112,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  homeProductThumb: {
    width: 72,
    height: 72,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.primaryPale,
  },
  homeProductThumbPlaceholder: {
    width: 72,
    height: 72,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.primaryPale,
    alignItems: "center",
    justifyContent: "center",
  },
  homeProductMain: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  homeProductTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
  },
  homeProductName: {
    flex: 1,
    minWidth: 0,
  },
  homeStoreLine: {
    color: C.primaryDeep,
    fontSize: 12,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  homeProductMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 2,
  },
  homeDeltaText: {
    color: C.primaryDeep,
    fontSize: 12,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  homeProductPriceCol: {
    width: 96,
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 8,
  },
  homeListBtn: {
    minHeight: 30,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.primary,
    backgroundColor: C.primaryGhost,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 9,
  },
  homeListBtnActive: {
    borderColor: C.primaryDeep,
    backgroundColor: C.white,
  },
  homeListBtnText: {
    color: C.primaryDeep,
    fontSize: 11,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  homeListBtnTextActive: {
    color: C.text,
  },
  homeShowMoreBtn: {
    minHeight: 46,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: C.primary,
    backgroundColor: C.primaryGhost,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
  },
  homeShowMoreText: {
    color: C.primaryDeep,
    fontSize: 13,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  dealCard: {
    width: "48.5%",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    overflow: "hidden",
  },
  dealCardActive: {
    borderColor: C.primary,
  },
  dealCardImage: {
    width: "100%",
    height: 112,
    backgroundColor: C.primaryPale,
  },
  dealCardImagePlaceholder: {
    width: "100%",
    height: 112,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.primaryPale,
  },
  dealCardBody: {
    padding: 10,
    gap: 4,
  },
  dealCardBottomRow: {
    marginTop: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  dealPrice: {
    color: C.text,
    fontSize: 20,
    fontWeight: "900",
    fontFamily: F.extraBold,
  },
  homePriceCurrentCard: {
    marginTop: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    padding: 8,
    gap: 2,
  },
  homePriceValue: {
    color: C.text,
    fontSize: 15,
    fontWeight: "900",
    fontFamily: F.extraBold,
  },
  homePriceStoreText: {
    color: C.textSoft,
    fontSize: 11,
    fontWeight: "700",
    fontFamily: F.bold,
    lineHeight: 15,
  },
  priceJudgmentGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  priceJudgmentCell: {
    width: "48%",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    padding: 10,
    backgroundColor: C.bg,
    gap: 4,
  },
});
