import { StyleSheet } from "react-native";
import { marketingPalette as C } from "../../shared/design/palette";
import { F } from "./fonts";

export const commonStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: C.bg,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 18,
  },
  sectionStack: {
    gap: 12,
  },
  sectionTitle: {
    color: C.text,
    fontSize: 24,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  sectionSub: {
    color: C.textSoft,
    fontSize: 14,
    lineHeight: 20,
    fontFamily: F.regular,
  },
  badge: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: C.primary,
    backgroundColor: C.primaryGhost,
    color: C.primaryDeep,
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 11,
    fontWeight: "800",
    fontFamily: F.extraBold,
    overflow: "hidden",
  },
  dealHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  dealFilterRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  searchCard: {
    borderRadius: 15,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    paddingHorizontal: 15,
    paddingVertical: 4,
  },
  dealSearchRow: {
    gap: 8,
  },
  searchAndAlertRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  sortOptionsScroll: {
    maxHeight: 42,
  },
  searchInput: {
    height: 52,
    color: C.text,
    fontSize: 16,
    fontFamily: F.semibold,
  },
  categoryRow: {
    flexDirection: "row",
    gap: 8,
  },
  homeSearchCard: {
    flex: 1,
  },
  searchAlertBtn: {
    width: 60,
    height: 60,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#071f12",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  searchAlertBadge: {
    position: "absolute",
    top: 7,
    right: 7,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 4,
    backgroundColor: "#EF4444",
    borderWidth: 2,
    borderColor: C.white,
    alignItems: "center",
    justifyContent: "center",
  },
  searchAlertBadgeText: {
    color: C.white,
    fontSize: 9,
    lineHeight: 11,
    fontFamily: F.extraBold,
  },
  categoryChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  categoryChipActive: {
    backgroundColor: C.primaryGhost,
    borderColor: C.primary,
  },
  categoryChipText: {
    color: C.textMuted,
    fontSize: 12,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  categoryChipTextActive: {
    color: C.primaryDeep,
  },
  summaryPanel: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    paddingHorizontal: 14,
    paddingVertical: 4,
  },
  summaryRow: {
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  summaryRowWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  summaryCard: {
    minWidth: 108,
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 3,
  },
  summaryRowDivider: {
    borderBottomWidth: 1,
    borderBottomColor: C.line,
  },
  summaryLabel: {
    color: C.textSoft,
    fontSize: 14,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  summaryValue: {
    color: C.primaryDeep,
    fontSize: 20,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  summaryValueSmall: {
    color: C.text,
    fontSize: 14,
  },
  rowCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    padding: 14,
    gap: 6,
  },
  rowCardActive: {
    borderColor: C.primary,
    backgroundColor: C.primaryGhost,
  },
  productRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  productMain: {
    flex: 1,
    gap: 4,
  },
  productThumb: {
    width: 72,
    height: 72,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
  },
  productThumbImage: {
    width: "100%",
    height: "100%",
  },
  productThumbPlaceholder: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.primaryGhost,
  },
  productThumbPlaceholderText: {
    color: C.primaryDeep,
    fontSize: 12,
    fontWeight: "800",
    fontFamily: F.extraBold,
    letterSpacing: 0.6,
  },
  productActionRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 4,
  },
  productActionBtn: {
    minHeight: 32,
    borderRadius: 9,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  productActionPrimary: {
    backgroundColor: C.primary,
    borderColor: C.primary,
  },
  productActionSecondary: {
    backgroundColor: C.white,
    borderColor: C.line,
  },
  productActionPrimaryText: {
    color: C.white,
    fontSize: 12,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  productActionSecondaryText: {
    color: C.text,
    fontSize: 12,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  detailActionRow: {
    flexDirection: "row",
    gap: 8,
  },
  detailActionBtn: {
    flex: 1,
  },
  detailNavBtn: {
    minHeight: 44,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  detailNavBtnAccent: {
    backgroundColor: C.primaryGhost,
    borderColor: C.primary,
  },
  detailNavText: {
    color: C.primaryDeep,
    fontSize: 13,
    fontWeight: "900",
    fontFamily: F.extraBold,
  },
});
