import { StyleSheet } from "react-native";
import { marketingPalette as C } from "../../shared/design/palette";
import { F } from "./fonts";

export const foodScanStyles = StyleSheet.create({
  foodScanStack: {
    gap: 14,
  },
  foodScanIntro: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.primaryGhost,
    padding: 16,
    gap: 6,
  },
  foodScanEyebrow: {
    color: C.primaryDeep,
    fontSize: 11,
    fontWeight: "800",
    fontFamily: F.extraBold,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  foodScanTitle: {
    color: C.text,
    fontSize: 22,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  foodScanModeRow: {
    flexDirection: "row",
    gap: 8,
  },
  foodScanModeButton: {
    minHeight: 48,
    flex: 1,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  foodScanModeButtonActive: {
    borderColor: C.primaryDeep,
    backgroundColor: C.primaryGhost,
  },
  foodScanModeText: {
    color: C.textSoft,
    fontSize: 13,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  foodScanModeTextActive: {
    color: C.primaryDeep,
  },
  foodScanCameraCard: {
    borderRadius: 20,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: "#071F12",
  },
  foodScanCamera: {
    width: "100%",
    height: 390,
  },
  foodScanPreview: {
    width: "100%",
    height: 390,
    backgroundColor: "#071F12",
  },
  foodScanGuide: {
    position: "absolute",
    left: 28,
    right: 28,
    top: 46,
    bottom: 46,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.82)",
    alignItems: "center",
    justifyContent: "flex-end",
    padding: 14,
  },
  foodScanGuideText: {
    color: C.white,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
    fontFamily: F.bold,
    textAlign: "center",
    backgroundColor: "rgba(7,31,18,0.72)",
    borderRadius: 10,
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  foodScanBarcodeBadge: {
    position: "absolute",
    top: 12,
    right: 12,
    borderRadius: 999,
    backgroundColor: "rgba(7,31,18,0.78)",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  foodScanBarcodeText: {
    color: C.white,
    fontSize: 11,
    fontFamily: F.bold,
  },
  foodScanCaptureRow: {
    flexDirection: "row",
    gap: 10,
  },
  foodScanAction: {
    minHeight: 50,
    flex: 1,
    borderRadius: 14,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  foodScanActionPrimary: {
    backgroundColor: C.primaryDeep,
    borderColor: C.primaryDeep,
  },
  foodScanActionSecondary: {
    backgroundColor: C.white,
    borderColor: C.line,
  },
  foodScanActionDisabled: {
    opacity: 0.5,
  },
  foodScanActionPrimaryText: {
    color: C.white,
    fontSize: 14,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  foodScanActionSecondaryText: {
    color: C.text,
    fontSize: 14,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  foodScanPermissionCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    padding: 18,
    gap: 10,
  },
  foodScanStatusCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    padding: 16,
    alignItems: "center",
    gap: 8,
  },
  foodScanErrorCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(168,57,57,0.28)",
    backgroundColor: "#FBEAEA",
    padding: 14,
    gap: 5,
  },
  foodScanErrorText: {
    color: "#8F3030",
    fontSize: 13,
    lineHeight: 18,
    fontFamily: F.semibold,
  },
  foodScanResultCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    padding: 16,
    gap: 13,
  },
  foodScanResultHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  foodScanResultIdentity: {
    minWidth: 0,
    flex: 1,
    gap: 3,
  },
  foodScanConfidence: {
    borderRadius: 999,
    backgroundColor: C.primaryGhost,
    color: C.primaryDeep,
    paddingHorizontal: 9,
    paddingVertical: 5,
    fontSize: 11,
    fontWeight: "800",
    fontFamily: F.extraBold,
    overflow: "hidden",
  },
  foodScanRipeness: {
    borderRadius: 14,
    backgroundColor: C.primaryGhost,
    padding: 13,
    gap: 4,
  },
  foodScanSection: {
    gap: 7,
  },
  foodScanSectionTitle: {
    color: C.text,
    fontSize: 14,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  foodScanBulletRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  foodScanBullet: {
    color: C.primaryDeep,
    fontSize: 16,
    lineHeight: 19,
    fontFamily: F.extraBold,
  },
  foodScanBulletText: {
    flex: 1,
    color: C.textSoft,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: F.regular,
  },
  foodScanSafetyCard: {
    borderRadius: 13,
    backgroundColor: "#FFF7E8",
    borderWidth: 1,
    borderColor: "rgba(180,120,20,0.24)",
    padding: 12,
    gap: 4,
  },
  foodScanSafetyTitle: {
    color: "#805513",
    fontSize: 12,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  foodScanSafetyText: {
    color: "#674918",
    fontSize: 12,
    lineHeight: 18,
    fontFamily: F.regular,
  },
  foodScanFootnote: {
    color: C.textMuted,
    fontSize: 11,
    lineHeight: 16,
    textAlign: "center",
    fontFamily: F.regular,
  },
});
