import { StyleSheet } from "react-native";
import { marketingPalette as C } from "../../shared/design/palette";
import { F } from "./fonts";

export const freezerStyles = StyleSheet.create({
  freezerPage: { gap: 20 },
  freezerIntroRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: C.line,
  },
  freezerIntroCopy: { flex: 1, minWidth: 0, gap: 4 },
  freezerIntroTitle: { color: C.text, fontSize: 20, lineHeight: 25, fontFamily: F.extraBold },
  freezerHelp: { color: C.textSoft, fontSize: 12, lineHeight: 17, fontFamily: F.regular },
  freezerAddButton: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    borderRadius: 11,
    paddingHorizontal: 13,
    backgroundColor: C.primaryDeep,
  },
  freezerAddButtonText: { color: C.white, fontSize: 13, fontFamily: F.bold },
  freezerSummaryRow: { flexDirection: "row", gap: 8 },
  freezerSummaryCard: {
    minWidth: 0,
    flex: 1,
    alignItems: "center",
    gap: 3,
    borderRadius: 13,
    paddingHorizontal: 7,
    paddingVertical: 12,
    backgroundColor: C.primaryGhost,
  },
  freezerSummaryValue: { color: C.text, fontSize: 19, fontFamily: F.extraBold },
  freezerSummaryLabel: { color: C.textSoft, fontSize: 9, fontFamily: F.semibold },
  freezerMessage: { borderRadius: 12, padding: 12, backgroundColor: C.primaryGhost },
  freezerMessageText: { color: C.textSoft, fontSize: 12, lineHeight: 17, fontFamily: F.semibold },
  freezerLoading: { minHeight: 150, alignItems: "center", justifyContent: "center", gap: 10 },
  freezerEmpty: {
    alignItems: "center",
    gap: 8,
    borderRadius: 16,
    paddingHorizontal: 22,
    paddingVertical: 28,
    backgroundColor: C.primaryGhost,
  },
  freezerEmptyTitle: { color: C.text, fontSize: 17, fontFamily: F.extraBold },
  freezerEmptyButton: {
    minHeight: 44,
    marginTop: 5,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    paddingHorizontal: 16,
    backgroundColor: C.primaryDeep,
  },
  freezerEmptyButtonText: { color: C.white, fontSize: 13, fontFamily: F.bold },
  freezerForm: { gap: 14, borderRadius: 16, padding: 16, backgroundColor: C.primaryGhost },
  freezerFormHeader: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  freezerFormHeaderCopy: { flex: 1, minWidth: 0, gap: 2 },
  freezerFormTitle: { color: C.text, fontSize: 17, fontFamily: F.extraBold },
  freezerTextButton: { minHeight: 44, justifyContent: "center", paddingHorizontal: 5 },
  freezerTextButtonLabel: { color: C.primaryDeep, fontSize: 12, fontFamily: F.bold },
  freezerField: { gap: 6 },
  freezerFieldLabel: { color: C.textSoft, fontSize: 11, fontFamily: F.bold },
  freezerFieldRow: { flexDirection: "row", gap: 10 },
  freezerQuantityField: { flex: 0.8 },
  freezerUnitField: { flex: 1.2 },
  freezerInput: {
    minHeight: 46,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.line,
    paddingHorizontal: 12,
    backgroundColor: C.white,
    color: C.text,
    fontSize: 14,
    fontFamily: F.semibold,
  },
  freezerNoteInput: { minHeight: 76, paddingTop: 12, textAlignVertical: "top" },
  freezerSegmentedControl: { flexDirection: "row", gap: 7 },
  freezerSegment: {
    minHeight: 44,
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
  },
  freezerSegmentSelected: { borderColor: C.primaryDeep, backgroundColor: C.primaryPale },
  freezerSegmentText: { color: C.textSoft, fontSize: 12, fontFamily: F.bold },
  freezerSegmentTextSelected: { color: C.primaryDeep },
  freezerPrimaryButton: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
    paddingHorizontal: 16,
    backgroundColor: C.primaryDeep,
  },
  freezerPrimaryButtonText: { color: C.white, fontSize: 14, fontFamily: F.extraBold },
  freezerButtonPressed: { opacity: 0.86 },
  freezerButtonDisabled: { opacity: 0.55 },
  freezerLists: { gap: 24 },
  freezerSection: { gap: 9 },
  freezerSectionHeader: { flexDirection: "row", alignItems: "center", gap: 7 },
  freezerSectionTitle: { flex: 1, color: C.text, fontSize: 17, fontFamily: F.extraBold },
  freezerSectionCount: {
    minWidth: 28,
    color: C.textSoft,
    fontSize: 12,
    textAlign: "right",
    fontFamily: F.bold,
  },
  freezerSectionEmpty: {
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: C.line,
    paddingVertical: 15,
    color: C.textMuted,
    fontSize: 12,
    fontFamily: F.regular,
  },
  freezerItemList: { borderTopWidth: 1, borderTopColor: C.line },
  freezerItemRow: {
    minHeight: 78,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: C.line,
  },
  freezerItemCopy: { flex: 1, minWidth: 0, gap: 2 },
  freezerItemName: { color: C.text, fontSize: 15, fontFamily: F.extraBold },
  freezerItemMeta: { color: C.textSoft, fontSize: 12, fontFamily: F.semibold },
  freezerExpiry: { color: C.textMuted, fontSize: 11, fontFamily: F.regular },
  freezerExpiryAttention: { color: "#9A5D16", fontFamily: F.bold },
  freezerItemNote: { color: C.textSoft, fontSize: 11, lineHeight: 15, fontFamily: F.regular },
  freezerItemActions: { flexDirection: "row", alignItems: "center" },
  freezerIconButton: { width: 40, minHeight: 44, alignItems: "center", justifyContent: "center" },
});
