import { StyleSheet } from "react-native";
import { marketingPalette as C } from "../../shared/design/palette";
import { F } from "./fonts";

export const productDetailStyles = StyleSheet.create({
  productDetailStack: { gap: 12 },
  productHeroCard: { borderRadius: 16, borderWidth: 1, borderColor: C.line, backgroundColor: C.white, overflow: "hidden" },
  productHeroImage: { width: "100%", height: 148, backgroundColor: C.primaryPale },
  productHeroPlaceholder: { width: "100%", height: 104, backgroundColor: C.primaryPale, alignItems: "center", justifyContent: "center", gap: 6 },
  productHeroPlaceholderText: { color: C.primaryDeep, fontSize: 18, fontFamily: F.extraBold, textAlign: "center" },
  productHeroPlaceholderSub: { color: C.textSoft, fontSize: 12, fontFamily: F.bold },
  productHeroBody: { padding: 14, gap: 12 },
  productHeroTitleRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12 },
  productHeroTitleBlock: { flex: 1, minWidth: 0, gap: 3 },
  productHeroName: { color: C.text, fontSize: 22, lineHeight: 27, fontFamily: F.extraBold },
  productHeroDecision: { minWidth: 68, borderRadius: 999, backgroundColor: C.primaryGhost, borderWidth: 1, borderColor: C.primary, color: C.primaryDeep, paddingHorizontal: 11, paddingVertical: 6, textAlign: "center", fontSize: 12, fontFamily: F.extraBold, overflow: "hidden" },
  productHeroStore: { color: C.primaryDeep, fontSize: 13, fontFamily: F.extraBold },
  productHeroPriceRow: { flexDirection: "row", alignItems: "stretch", justifyContent: "space-between", gap: 12 },
  productHeroPrice: { color: C.text, fontSize: 34, lineHeight: 38, fontFamily: F.extraBold },
  productHeroChangeCard: { minWidth: 112, borderRadius: 12, borderWidth: 1, borderColor: C.line, backgroundColor: C.bg, paddingHorizontal: 10, paddingVertical: 8, justifyContent: "center", gap: 2 },
  productHeroChange: { color: C.text, fontSize: 18, fontFamily: F.extraBold },
  productDecisionText: { color: C.text, fontSize: 14, lineHeight: 20, fontFamily: F.extraBold },
  productHeroActions: { flexDirection: "row", gap: 8, alignItems: "stretch" },
  productHeroPrimaryAction: { flex: 1 },
  productHeroSecondaryAction: { minWidth: 120 },
  watchlistCtaBtn: { minHeight: 48, borderRadius: 13, borderWidth: 1, borderColor: C.primary, backgroundColor: C.primary, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  watchlistCtaText: { color: C.white, fontSize: 14, fontFamily: F.extraBold },
  watchlistSecondaryBtn: { minHeight: 48, borderRadius: 13, borderWidth: 1, borderColor: C.line, backgroundColor: C.white, alignItems: "center", justifyContent: "center", paddingHorizontal: 13 },
  watchlistSecondaryText: { color: C.text, fontSize: 13, fontFamily: F.extraBold },
  watchlistCtaHelp: { color: C.textSoft, fontSize: 12, lineHeight: 17, fontFamily: F.regular },
  productTrendCard: { borderRadius: 16, borderWidth: 1, borderColor: C.line, backgroundColor: C.white, padding: 14, gap: 10 },
  productStoreComparisonCard: { borderRadius: 16, borderWidth: 1, borderColor: C.line, backgroundColor: C.white, padding: 14, gap: 10 },
  productTrendHeading: { color: C.text, fontSize: 19, fontFamily: F.extraBold },
  productInfoGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  productInfoCell: { width: "48%", minHeight: 72, borderRadius: 12, borderWidth: 1, borderColor: C.line, backgroundColor: C.white, padding: 10, justifyContent: "center", gap: 3 },
});
