import { StyleSheet } from "react-native";
import { marketingPalette as C } from "../../shared/design/palette";
import { F } from "./fonts";

export const productHistoryStyles = StyleSheet.create({
  dealText: { color: C.primaryDeep, fontSize: 13, fontFamily: F.extraBold },
  bestStoreRow: { borderColor: C.primary, backgroundColor: C.primaryGhost },
  storeChartCard: { borderRadius: 12, borderWidth: 1, borderColor: C.line, backgroundColor: C.bg, padding: 10, gap: 10 },
  storeChartRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  storeChartLabelWrap: { width: 82, gap: 2 },
  storeChartLabel: { color: C.text, fontSize: 11, fontFamily: F.extraBold },
  storeChartBest: { color: C.primaryDeep, fontSize: 10, fontFamily: F.extraBold },
  storeChartTrack: { flex: 1, height: 18, borderRadius: 999, overflow: "hidden", backgroundColor: C.white, borderWidth: 1, borderColor: C.line },
  storeChartBar: { height: "100%", borderRadius: 999, backgroundColor: C.textMuted },
  storeChartBarBest: { backgroundColor: C.primary },
  storeChartPrice: { minWidth: 54, textAlign: "right", color: C.text, fontSize: 11, fontFamily: F.extraBold },
  chartWrap: { borderRadius: 12, borderWidth: 1, borderColor: C.line, backgroundColor: C.bg, padding: 8, alignItems: "center", justifyContent: "center" },
  chartMetaRow: { flexDirection: "row", justifyContent: "space-between", gap: 10 },
  chartMetaText: { color: C.textMuted, fontSize: 12, fontFamily: F.bold },
  periodLowestRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, borderRadius: 10, borderWidth: 1, borderColor: C.line, backgroundColor: C.bg, paddingHorizontal: 12, paddingVertical: 10 },
  periodLowestMain: { flex: 1, minWidth: 0, gap: 4 },
  periodLowestLabelRow: { flexDirection: "row", alignItems: "center", gap: 7 },
  periodLatestBadge: { borderRadius: 999, overflow: "hidden", backgroundColor: C.primaryGhost, color: C.primaryDeep, fontSize: 10, fontFamily: F.extraBold, paddingHorizontal: 7, paddingVertical: 2 },
  periodLowestStore: { color: C.text, fontSize: 13, fontFamily: F.extraBold },
  periodLowestPriceBlock: { alignItems: "flex-end", gap: 2 },
  historyTitle: { color: C.text, fontSize: 14, fontFamily: F.extraBold, marginTop: 4 },
  historyRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10, borderRadius: 10, borderWidth: 1, borderColor: C.line, backgroundColor: C.bg, paddingHorizontal: 10, paddingVertical: 8 },
  storeCompareRow: { gap: 10, borderRadius: 10, borderWidth: 1, borderColor: C.line, backgroundColor: C.bg, padding: 12 },
  storeCompareTopRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12 },
  storeCompareTitleBlock: { flex: 1, minWidth: 0, gap: 3 },
  storeCompareName: { color: C.text, fontSize: 15, fontFamily: F.extraBold },
  storeCompareBranchText: { color: C.textSoft, fontSize: 12, fontFamily: F.bold },
  storeComparePriceBlock: { alignItems: "flex-end", gap: 3 },
  storeCompareLowest: { color: C.primaryDeep, fontSize: 12, fontFamily: F.extraBold },
  storeCompareMetaRow: { borderTopWidth: 1, borderTopColor: C.line, paddingTop: 8, gap: 3 },
  storeCompareTrendText: { color: C.primaryDeep, fontSize: 12, fontFamily: F.extraBold },
  historyLabel: { color: C.textMuted, fontSize: 12, fontFamily: F.bold },
  historyPrice: { color: C.text, fontSize: 13, fontFamily: F.bold },
  historyDiff: { fontSize: 12, fontFamily: F.bold },
  historyDiffUp: { color: "#A83939" },
  historyDiffDown: { color: C.primaryDeep },
  watchRowTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  watchRowMain: { flex: 1, gap: 4 },
  removeBtn: { minHeight: 44, borderRadius: 8, borderWidth: 1, borderColor: "#D9A0A0", backgroundColor: "#FFF0F0", alignItems: "center", justifyContent: "center", paddingHorizontal: 12 },
  removeBtnDisabled: { opacity: 0.6 },
  removeBtnText: { color: "#A83939", fontSize: 12, fontFamily: F.bold },
});
