import { StyleSheet } from "react-native";
import { marketingPalette as C } from "../../shared/design/palette";
import { F } from "./fonts";

export const productDetailStyles = StyleSheet.create({
  productDetailStack: {
    gap: 12,
  },
  productHeroCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    overflow: "hidden",
  },
  productHeroImage: {
    width: "100%",
    height: 220,
    backgroundColor: C.primaryPale,
  },
  productHeroPlaceholder: {
    width: "100%",
    height: 220,
    backgroundColor: C.primaryPale,
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  productHeroPlaceholderText: {
    color: C.primaryDeep,
    fontSize: 18,
    fontWeight: "900",
    fontFamily: F.extraBold,
    textAlign: "center",
  },
  productHeroPlaceholderSub: {
    color: C.textSoft,
    fontSize: 12,
    fontWeight: "800",
    fontFamily: F.bold,
  },
  productHeroBody: {
    padding: 14,
    gap: 12,
  },
  productHeroTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  productHeroTitleBlock: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  productHeroName: {
    color: C.text,
    fontSize: 22,
    lineHeight: 27,
    fontWeight: "900",
    fontFamily: F.extraBold,
  },
  productHeroDecision: {
    minWidth: 68,
    borderRadius: 999,
    backgroundColor: C.primaryGhost,
    borderWidth: 1,
    borderColor: C.primary,
    color: C.primaryDeep,
    paddingHorizontal: 11,
    paddingVertical: 6,
    textAlign: "center",
    fontSize: 12,
    fontWeight: "900",
    fontFamily: F.extraBold,
    overflow: "hidden",
  },
  productHeroStore: {
    color: C.primaryDeep,
    fontSize: 13,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  productHeroPriceRow: {
    flexDirection: "row",
    alignItems: "stretch",
    justifyContent: "space-between",
    gap: 12,
  },
  productHeroPrice: {
    color: C.text,
    fontSize: 34,
    lineHeight: 38,
    fontWeight: "900",
    fontFamily: F.extraBold,
  },
  productHeroChangeCard: {
    minWidth: 112,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    paddingHorizontal: 10,
    paddingVertical: 8,
    justifyContent: "center",
    gap: 2,
  },
  productHeroChange: {
    color: C.text,
    fontSize: 18,
    fontWeight: "900",
    fontFamily: F.extraBold,
  },
  productDecisionText: {
    color: C.text,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  productHeroActions: {
    flexDirection: "row",
    gap: 8,
  },
  productHeroPrimaryAction: {
    flex: 1,
  },
  productHeroSecondaryAction: {
    minWidth: 108,
  },
  watchlistCtaBtn: {
    minHeight: 48,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: C.primary,
    backgroundColor: C.primary,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  watchlistCtaText: {
    color: C.white,
    fontSize: 14,
    fontWeight: "900",
    fontFamily: F.extraBold,
  },
  watchlistSecondaryBtn: {
    minHeight: 48,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 13,
  },
  watchlistSecondaryText: {
    color: C.text,
    fontSize: 13,
    fontWeight: "900",
    fontFamily: F.extraBold,
  },
  watchlistCtaHelp: {
    color: C.textSoft,
    fontSize: 12,
    lineHeight: 17,
    fontFamily: F.regular,
  },
  productInfoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  productInfoCell: {
    width: "48%",
    minHeight: 72,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    padding: 10,
    justifyContent: "center",
    gap: 3,
  },
  dealSummaryGrid: {
    flexDirection: "row",
    gap: 10,
  },
  dealSummaryCell: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    padding: 10,
    gap: 4,
  },
  dealValueGood: {
    color: C.primaryDeep,
  },
  dealValueNeutral: {
    color: C.text,
  },
  dealText: {
    color: C.primaryDeep,
    fontSize: 13,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  targetRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  targetInput: {
    flex: 1,
  },
  targetSaveBtn: {
    minWidth: 92,
  },
  bestStoreRow: {
    borderColor: C.primary,
    backgroundColor: C.primaryGhost,
  },
  storeChartCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    padding: 10,
    gap: 10,
  },
  storeChartRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  storeChartLabelWrap: {
    width: 82,
    gap: 2,
  },
  storeChartLabel: {
    color: C.text,
    fontSize: 11,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  storeChartBest: {
    color: C.primaryDeep,
    fontSize: 10,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  storeChartTrack: {
    flex: 1,
    height: 18,
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.line,
  },
  storeChartBar: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: C.textMuted,
  },
  storeChartBarBest: {
    backgroundColor: C.primary,
  },
  storeChartPrice: {
    minWidth: 54,
    textAlign: "right",
    color: C.text,
    fontSize: 11,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  chartWrap: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    padding: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  chartMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  chartMetaText: {
    color: C.textMuted,
    fontSize: 12,
    fontFamily: F.bold,
  },
  periodLowestRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  periodLowestMain: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  periodLowestLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  periodLatestBadge: {
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: C.primaryGhost,
    color: C.primaryDeep,
    fontSize: 10,
    fontWeight: "900",
    fontFamily: F.extraBold,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  periodLowestStore: {
    color: C.text,
    fontSize: 13,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  periodLowestPriceBlock: {
    alignItems: "flex-end",
    gap: 2,
  },
  historyTitle: {
    color: C.text,
    fontSize: 14,
    fontWeight: "800",
    fontFamily: F.extraBold,
    marginTop: 4,
  },
  historyRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  storeCompareRow: {
    gap: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    padding: 12,
  },
  storeCompareTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  storeCompareTitleBlock: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  storeCompareName: {
    color: C.text,
    fontSize: 15,
    fontWeight: "900",
    fontFamily: F.extraBold,
  },
  storeCompareBranchText: {
    color: C.textSoft,
    fontSize: 12,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  storeComparePriceBlock: {
    alignItems: "flex-end",
    gap: 3,
  },
  storeCompareLowest: {
    color: C.primaryDeep,
    fontSize: 12,
    fontWeight: "900",
    fontFamily: F.extraBold,
  },
  storeCompareMetaRow: {
    borderTopWidth: 1,
    borderTopColor: C.line,
    paddingTop: 8,
    gap: 3,
  },
  storeCompareTrendText: {
    color: C.primaryDeep,
    fontSize: 12,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  storeRowRight: {
    alignItems: "flex-end",
    gap: 2,
  },
  historyLabel: {
    color: C.textMuted,
    fontSize: 12,
    fontFamily: F.bold,
  },
  historyPrice: {
    color: C.text,
    fontSize: 13,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  historyDiff: {
    fontSize: 12,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  historyDiffUp: {
    color: "#A83939",
  },
  historyDiffDown: {
    color: C.primaryDeep,
  },
  watchRowTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  watchRowMain: {
    flex: 1,
    gap: 4,
  },
  removeBtn: {
    minHeight: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#D9A0A0",
    backgroundColor: "#FFF0F0",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  removeBtnDisabled: {
    opacity: 0.6,
  },
  removeBtnText: {
    color: "#A83939",
    fontSize: 12,
    fontWeight: "700",
    fontFamily: F.bold,
  },
});
