import { StyleSheet } from "react-native";
import { marketingPalette as C } from "../../shared/design/palette";
import { F } from "./fonts";

export const productPriceTrendStyles = StyleSheet.create({
  trendHeadingRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  trendHeading: { color: C.text, fontSize: 20, fontFamily: F.bold },
  trendCaption: { color: C.textMuted, fontSize: 12, fontFamily: F.regular },
  trendSummary: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginVertical: 6,
  },
  trendSummaryPriceBlock: { gap: 2 },
  trendPrice: {
    color: C.text,
    fontSize: 36,
    fontFamily: F.bold,
    fontVariant: ["tabular-nums"],
    letterSpacing: -1,
  },
  trendChangeBlock: { alignItems: "flex-end", gap: 2 },
  trendChange: {
    color: C.textMuted,
    fontSize: 16,
    fontFamily: F.semibold,
    fontVariant: ["tabular-nums"],
  },
  trendChangeCaption: { color: C.textMuted, fontSize: 11, fontFamily: F.regular },
  trendChartWrap: { alignSelf: "stretch", marginVertical: 4 },
  trendRange: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 8,
  },
  trendRangePrice: { color: C.text, fontFamily: F.semibold, fontVariant: ["tabular-nums"] },
  trendSelectedSection: { borderTopWidth: 1, borderTopColor: C.line, paddingTop: 4, gap: 4 },
  trendPeriodNavigation: { flexDirection: "row", alignItems: "center", gap: 4 },
  trendPeriodButton: { width: 44, minHeight: 44, alignItems: "center", justifyContent: "center" },
  trendDisabled: { opacity: 0.3 },
  trendPeriodLabel: {
    flex: 1,
    color: C.textMuted,
    fontSize: 12,
    fontFamily: F.regular,
    textAlign: "center",
  },
  trendSelectedRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  trendSelectedRetailer: { flex: 1, color: C.text, fontSize: 14, fontFamily: F.semibold },
  trendSelectedPrice: {
    color: C.text,
    fontSize: 20,
    fontFamily: F.bold,
    fontVariant: ["tabular-nums"],
  },
  trendCompareButton: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    minHeight: 44,
  },
  trendCompareLabel: { color: C.primaryDeep, fontSize: 12, fontFamily: F.semibold },
  trendRetailerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: C.line,
  },
  trendRetailerNameBlock: { flex: 1, gap: 2 },
  trendRetailerName: { color: C.textSoft, fontSize: 12, fontFamily: F.regular },
  trendRetailerPrice: {
    color: C.text,
    fontSize: 13,
    fontFamily: F.semibold,
    fontVariant: ["tabular-nums"],
  },
});
