import { StyleSheet } from "react-native";
import { marketingPalette as C } from "../../shared/design/palette";
import { F } from "./fonts";

export const shoppingListStyles = StyleSheet.create({
  listPageStack: { gap: 28 },
  listSectionDivider: { height: 1, backgroundColor: C.line },
  shoppingDetailAddBtn: { minHeight: 48, borderRadius: 13, borderWidth: 1, borderColor: C.primary, backgroundColor: C.primaryGhost, alignItems: "center", justifyContent: "center", paddingHorizontal: 14 },
  shoppingDetailAddBtnActive: { backgroundColor: C.white, borderColor: C.primaryDeep },
  shoppingDetailAddText: { color: C.primaryDeep, fontSize: 14, fontFamily: F.extraBold },
  shoppingDetailAddTextActive: { color: C.text },
  shoppingHeaderRow: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
  shoppingHeaderCopy: { flex: 1, gap: 4 },
  shoppingClearBtn: { borderRadius: 9, borderWidth: 1, borderColor: C.line, paddingHorizontal: 10, paddingVertical: 7, backgroundColor: C.white },
  shoppingClearText: { color: C.textSoft, fontSize: 12, fontFamily: F.bold },
  shoppingEmptyCard: { borderRadius: 16, borderWidth: 1, borderColor: C.primary, backgroundColor: C.primaryGhost, padding: 18, gap: 6 },
  shoppingItemsCard: { borderRadius: 16, borderWidth: 1, borderColor: C.line, backgroundColor: C.white, paddingHorizontal: 14 },
  shoppingItemRow: { minHeight: 76, flexDirection: "row", alignItems: "center", gap: 9, paddingVertical: 11 },
  shoppingItemDivider: { borderTopWidth: 1, borderTopColor: C.line },
  shoppingItemCopy: { flex: 1, minWidth: 0, gap: 2 },
  quantityControl: { flexDirection: "row", alignItems: "center", borderRadius: 10, borderWidth: 1, borderColor: C.line, overflow: "hidden" },
  quantityBtn: { width: 32, height: 34, alignItems: "center", justifyContent: "center", backgroundColor: C.bg },
  quantityBtnText: { color: C.primaryDeep, fontSize: 20, lineHeight: 22, fontFamily: F.extraBold },
  quantityValue: { minWidth: 30, textAlign: "center", color: C.text, fontSize: 14, fontFamily: F.extraBold },
  shoppingRemoveBtn: { paddingVertical: 8 },
  shoppingRemoveText: { color: C.textMuted, fontSize: 11, fontFamily: F.bold },
  shoppingRecommendationCard: { borderRadius: 18, borderWidth: 1, borderColor: C.primary, backgroundColor: C.primaryGhost, padding: 15, gap: 11 },
  shoppingPlanTitleRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 10 },
  shoppingEyebrow: { color: C.primaryDeep, fontSize: 10, letterSpacing: 1.2, fontFamily: F.extraBold },
  shoppingPlanTitle: { color: C.text, fontSize: 21, fontFamily: F.extraBold, marginTop: 3 },
  shoppingRefreshBtn: { borderRadius: 9, backgroundColor: C.white, borderWidth: 1, borderColor: C.primary, paddingHorizontal: 10, paddingVertical: 7 },
  shoppingRefreshText: { color: C.primaryDeep, fontSize: 11, fontFamily: F.extraBold },
  shoppingSavingsText: { color: C.primaryDeep, fontSize: 14, lineHeight: 20, fontFamily: F.extraBold },
  shoppingWarningText: { color: C.textSoft, fontSize: 12, lineHeight: 17, fontFamily: F.semibold },
  shoppingStops: { gap: 8 },
  shoppingStopCard: { borderRadius: 13, backgroundColor: C.white, borderWidth: 1, borderColor: C.line, padding: 12, gap: 7 },
  shoppingStopHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 10 },
  shoppingStopCopy: { flex: 1, minWidth: 0, gap: 2 },
  shoppingStopNumber: { color: C.primaryDeep, fontSize: 9, letterSpacing: 0.8, fontFamily: F.extraBold },
  shoppingStopPriceCol: { alignItems: "flex-end", gap: 4 },
  shoppingMapLink: { color: C.primaryDeep, fontSize: 11, textDecorationLine: "underline", fontFamily: F.bold },
  shoppingCompareRow: { flexDirection: "row", gap: 8 },
  shoppingCompareCard: { flex: 1, borderRadius: 14, borderWidth: 1, borderColor: C.line, backgroundColor: C.white, padding: 12, gap: 4 },
  shoppingCompareValue: { color: C.text, fontSize: 18, fontFamily: F.extraBold },
  shoppingFootnote: { color: C.textMuted, fontSize: 11, lineHeight: 16, fontFamily: F.regular },
});
