import { StyleSheet } from "react-native";
import { marketingPalette as C } from "../../shared/design/palette";
import { F } from "./fonts";

export const shoppingListStyles = StyleSheet.create({
  shoppingPage: {
    gap: 18,
  },
  listPageStack: { gap: 28 },
  listSectionDivider: { height: 1, backgroundColor: C.line },
  shoppingDetailAddBtn: {
    minHeight: 48,
    borderRadius: 13,
    backgroundColor: C.primaryGhost,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  shoppingDetailAddBtnActive: { backgroundColor: C.primaryPale },
  shoppingDetailAddText: { color: C.primaryDeep, fontSize: 14, fontFamily: F.extraBold },
  shoppingDetailAddTextActive: { color: C.text },
  shoppingHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: C.line,
  },
  shoppingHeaderCopy: { flex: 1, gap: 4 },
  shoppingClearBtn: {
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: C.primaryGhost,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  shoppingClearText: { color: C.textSoft, fontSize: 12, fontFamily: F.bold },
  shoppingEmptyCard: {
    borderRadius: 16,
    backgroundColor: C.primaryGhost,
    padding: 18,
    gap: 8,
  },
  shoppingEmptyAction: {
    minHeight: 48,
    marginTop: 6,
    borderRadius: 12,
    backgroundColor: C.primary,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  shoppingEmptyActionText: { color: C.white, fontSize: 14, fontFamily: F.extraBold },
  shoppingSectionTitle: {
    color: C.text,
    fontSize: 18,
    fontFamily: F.extraBold,
  },
  shoppingItemsCard: {
    borderTopWidth: 1,
    borderTopColor: C.line,
  },
  shoppingItemRow: {
    minHeight: 76,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: C.line,
  },
  shoppingItemCopy: { flex: 1, minWidth: 0, gap: 2 },
  quantityControl: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 10,
    overflow: "hidden",
    backgroundColor: C.primaryGhost,
  },
  quantityBtn: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  quantityBtnText: { color: C.primaryDeep, fontSize: 20, lineHeight: 22, fontFamily: F.extraBold },
  quantityValue: {
    minWidth: 30,
    textAlign: "center",
    color: C.text,
    fontSize: 14,
    fontFamily: F.extraBold,
  },
  shoppingRemoveBtn: {
    width: 36,
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  shoppingRecommendationCard: {
    borderRadius: 18,
    backgroundColor: C.primaryGhost,
    padding: 16,
    gap: 12,
  },
  shoppingPlanTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  shoppingEyebrow: {
    color: C.primaryDeep,
    fontSize: 10,
    letterSpacing: 1.2,
    fontFamily: F.extraBold,
  },
  shoppingPlanTitle: { color: C.text, fontSize: 21, fontFamily: F.extraBold, marginTop: 3 },
  shoppingRefreshBtn: {
    minHeight: 44,
    borderRadius: 9,
    backgroundColor: C.white,
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  shoppingRefreshText: { color: C.primaryDeep, fontSize: 11, fontFamily: F.extraBold },
  shoppingSavingsText: {
    color: C.primaryDeep,
    fontSize: 14,
    lineHeight: 20,
    fontFamily: F.extraBold,
  },
  shoppingWarningText: { color: C.textSoft, fontSize: 12, lineHeight: 17, fontFamily: F.semibold },
  shoppingStops: {
    borderTopWidth: 1,
    borderTopColor: C.line,
  },
  shoppingStopCard: {
    paddingVertical: 13,
    gap: 7,
    borderBottomWidth: 1,
    borderBottomColor: C.line,
  },
  shoppingStopHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 10,
  },
  shoppingStopCopy: { flex: 1, minWidth: 0, gap: 2 },
  shoppingStopNumber: {
    color: C.primaryDeep,
    fontSize: 9,
    letterSpacing: 0.8,
    fontFamily: F.extraBold,
  },
  shoppingStopPriceCol: { alignItems: "flex-end", gap: 4 },
  shoppingMapButton: {
    minHeight: 44,
    minWidth: 70,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  shoppingMapLink: {
    color: C.primaryDeep,
    fontSize: 11,
    textDecorationLine: "underline",
    fontFamily: F.bold,
  },
  shoppingCompareRow: {
    borderTopWidth: 1,
    borderTopColor: C.line,
  },
  shoppingCompareCard: {
    paddingVertical: 13,
    gap: 4,
    borderBottomWidth: 1,
    borderBottomColor: C.line,
  },
  shoppingCompareTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  shoppingCompareValue: { color: C.text, fontSize: 18, fontFamily: F.extraBold },
  shoppingFootnote: { color: C.textMuted, fontSize: 11, lineHeight: 16, fontFamily: F.regular },
});
