import { StyleSheet } from "react-native";
import { marketingPalette as C } from "../../shared/design/palette";
import { F } from "./fonts";

export const storeMapStyles = StyleSheet.create({
  storeMapScreen: {
    flex: 1,
    backgroundColor: "#DCE9E3",
  },
  storeMapCanvas: {
    ...StyleSheet.absoluteFillObject,
  },
  storeMapControlsOverlay: {
    position: "absolute",
    zIndex: 5,
    top: 0,
    left: 0,
    right: 0,
    gap: 10,
  },
  storeMapControlsList: {
    gap: 10,
    paddingBottom: 12,
    backgroundColor: C.white,
  },
  storeMapSearchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  storeMapSearchBox: {
    minWidth: 0,
    flex: 1,
    height: 58,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: 29,
    borderWidth: 1,
    borderColor: "#D6DDDA",
    backgroundColor: C.white,
    paddingHorizontal: 18,
    shadowColor: "#10281F",
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 5 },
    elevation: 7,
  },
  storeMapSearchInput: {
    minWidth: 0,
    flex: 1,
    height: "100%",
    color: C.text,
    fontSize: 16,
    fontFamily: F.semibold,
  },
  storeMapClearButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.bg,
  },
  storeMapClearText: {
    marginTop: -2,
    color: C.textMuted,
    fontSize: 24,
    lineHeight: 26,
    fontFamily: F.regular,
  },
  storeMapLocationButton: {
    width: 58,
    height: 58,
    borderRadius: 29,
    borderWidth: 1,
    borderColor: "#D6DDDA",
    backgroundColor: C.white,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#10281F",
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 5 },
    elevation: 7,
  },
  storeMapLocationButtonActive: {
    borderColor: C.primary,
    backgroundColor: C.primaryGhost,
  },
  storeMapFilterRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingRight: 12,
  },
  storeMapFilterButton: {
    height: 42,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderRadius: 21,
    borderWidth: 1,
    borderColor: "#D6DDDA",
    backgroundColor: C.white,
    paddingHorizontal: 15,
    shadowColor: "#10281F",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  storeMapFilterButtonActive: {
    borderColor: C.primary,
    backgroundColor: C.primaryGhost,
  },
  storeMapFilterText: {
    color: C.text,
    fontSize: 13,
    fontFamily: F.bold,
  },
  storeMapMarker: {
    minWidth: 46,
    height: 46,
    borderRadius: 23,
    borderWidth: 3,
    borderColor: C.white,
    backgroundColor: C.primaryDeep,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 7,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 3 },
    elevation: 6,
  },
  storeMapMarkerWrap: {
    alignItems: "center",
    justifyContent: "center",
  },
  storeMapMarkerActive: {
    minWidth: 54,
    height: 54,
    borderRadius: 27,
    borderColor: C.primaryDeep,
    backgroundColor: C.white,
  },
  storeMapMarkerWithLogo: {
    overflow: "hidden",
    backgroundColor: C.white,
    paddingHorizontal: 4,
  },
  storeMapMarkerImage: {
    width: "100%",
    height: "100%",
  },
  storeMapMarkerText: {
    color: C.white,
    fontSize: 13,
    fontFamily: F.extraBold,
  },
  storeMapMarkerTextActive: {
    color: C.primaryDeep,
    fontSize: 15,
  },
  storeMapClusterMarker: {
    minWidth: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 3,
    borderColor: C.white,
    backgroundColor: C.primaryDeep,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 3 },
    elevation: 6,
  },
  storeMapClusterMarkerFavorite: {
    borderColor: C.primary,
  },
  storeMapClusterMarkerText: {
    color: C.white,
    fontSize: 17,
    fontFamily: F.extraBold,
  },
  storeMapMarkerFavoriteBadge: {
    position: "absolute",
    top: -5,
    right: -5,
    width: 19,
    height: 19,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: C.white,
    backgroundColor: C.primaryDeep,
    alignItems: "center",
    justifyContent: "center",
  },
  storeMapBottomSheet: {
    position: "absolute",
    zIndex: 6,
    left: 0,
    right: 0,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    backgroundColor: C.white,
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 14,
    shadowColor: "#10281F",
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: -5 },
    elevation: 12,
  },
  storeMapSheetHandle: {
    alignSelf: "center",
    width: 42,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#CAD4D0",
    marginBottom: 9,
  },
  storeMapSheetHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 10,
  },
  storeMapSheetTitle: {
    color: C.text,
    fontSize: 18,
    fontFamily: F.extraBold,
  },
  storeMapSheetSubtitle: {
    marginTop: 2,
    color: C.textMuted,
    fontSize: 11,
    fontFamily: F.regular,
  },
  storeMapModeButton: {
    minWidth: 82,
    height: 42,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderRadius: 21,
    backgroundColor: C.primaryDeep,
    paddingHorizontal: 14,
  },
  storeMapModeButtonText: {
    color: C.white,
    fontSize: 14,
    fontFamily: F.extraBold,
  },
  storeMapMessage: {
    color: "#A83939",
    fontSize: 11,
    lineHeight: 16,
    fontFamily: F.semibold,
    marginBottom: 8,
  },
  storeResultCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    overflow: "hidden",
    shadowColor: "#10281F",
    shadowOpacity: 0.09,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  storeResultCardActive: {
    borderColor: "#B5D4C8",
  },
  storeResultCardCompact: {
    shadowOpacity: 0,
    elevation: 0,
  },
  storeResultMain: {
    minHeight: 78,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 13,
    paddingVertical: 10,
  },
  storeResultFocusContent: {
    minWidth: 0,
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  storeFavoriteButton: {
    width: 38,
    height: 38,
    marginLeft: 8,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    alignItems: "center",
    justifyContent: "center",
  },
  storeFavoriteButtonActive: {
    borderColor: C.primary,
    backgroundColor: C.primaryGhost,
  },
  storeResultBadge: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.primaryGhost,
    borderWidth: 2,
    borderColor: C.primary,
  },
  storeResultBadgeWithLogo: {
    overflow: "hidden",
    backgroundColor: C.white,
    padding: 4,
  },
  storeResultLogo: {
    width: "100%",
    height: "100%",
  },
  storeResultBadgeText: {
    color: C.primaryDeep,
    fontSize: 14,
    fontFamily: F.extraBold,
  },
  storeResultCopy: {
    minWidth: 0,
    flex: 1,
    gap: 3,
  },
  storeResultName: {
    color: C.text,
    fontSize: 15,
    fontFamily: F.extraBold,
  },
  storeResultAddress: {
    color: C.textSoft,
    fontSize: 12,
    fontFamily: F.regular,
  },
  storeResultMetaRow: {
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  storeResultDistance: {
    color: C.primaryDeep,
    fontSize: 11,
    fontFamily: F.bold,
  },
  storeResultDivider: {
    width: 1,
    height: 12,
    backgroundColor: C.line,
  },
  storeResultPrice: {
    minWidth: 0,
    flexShrink: 1,
    color: C.textMuted,
    fontSize: 11,
    fontFamily: F.semibold,
  },
  storeResultDealsButton: {
    height: 38,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: C.line,
    paddingHorizontal: 14,
  },
  storeResultDealsText: {
    color: C.primaryDeep,
    fontSize: 12,
    fontFamily: F.extraBold,
  },
  storeResultDealsArrow: {
    color: C.primaryDeep,
    fontSize: 24,
    lineHeight: 26,
    fontFamily: F.regular,
  },
  storeListScreen: {
    flex: 1,
    backgroundColor: C.white,
  },
  storeListScroll: {
    flex: 1,
  },
  storeListHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingTop: 4,
    paddingBottom: 14,
  },
  storeListTitle: {
    color: C.text,
    fontSize: 22,
    fontFamily: F.extraBold,
  },
  storeListSubtitle: {
    marginTop: 3,
    color: C.textMuted,
    fontSize: 11,
    fontFamily: F.regular,
  },
  storeListCardSeparator: {
    height: 12,
  },
  storeMapEmptyCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    padding: 20,
    marginBottom: 12,
  },
  storeMapEmptyTitle: {
    color: C.text,
    fontSize: 16,
    fontFamily: F.extraBold,
  },
  storeMapEmptyText: {
    marginTop: 3,
    color: C.textMuted,
    fontSize: 12,
    lineHeight: 17,
    fontFamily: F.regular,
  },
});
