import { StyleSheet } from "react-native";
import { marketingPalette as C } from "../../shared/design/palette";
import { F } from "./fonts";

export const storeMapStyles = StyleSheet.create({
  storeMapScreen: { flex: 1, backgroundColor: "#DCE9E3" },
  storeMapCanvas: { ...StyleSheet.absoluteFillObject },
  storeMapControlsOverlay: { position: "absolute", zIndex: 5, top: 0, left: 0, right: 0, gap: 10 },
  storeMapControlsList: { gap: 10, paddingBottom: 12, backgroundColor: C.white },
  storeMapSearchRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  storeMapSearchBox: { minWidth: 0, flex: 1, height: 58, flexDirection: "row", alignItems: "center", gap: 10, borderRadius: 29, borderWidth: 1, borderColor: "#D6DDDA", backgroundColor: C.white, paddingHorizontal: 18, shadowColor: "#10281F", shadowOpacity: 0.12, shadowRadius: 14, shadowOffset: { width: 0, height: 5 }, elevation: 7 },
  storeMapSearchInput: { minWidth: 0, flex: 1, height: "100%", color: C.text, fontSize: 16, fontFamily: F.semibold },
  storeMapClearButton: { width: 44, height: 44, borderRadius: 22, alignItems: "center", justifyContent: "center", backgroundColor: C.bg },
  storeMapClearText: { marginTop: -2, color: C.textMuted, fontSize: 24, lineHeight: 26, fontFamily: F.regular },
  storeMapLocationButton: { width: 58, height: 58, borderRadius: 29, borderWidth: 1, borderColor: "#D6DDDA", backgroundColor: C.white, alignItems: "center", justifyContent: "center", shadowColor: "#10281F", shadowOpacity: 0.12, shadowRadius: 14, shadowOffset: { width: 0, height: 5 }, elevation: 7 },
  storeMapLocationButtonActive: { borderColor: C.primary, backgroundColor: C.primaryGhost },
  storeMapFilterRow: { flexDirection: "row", alignItems: "center", gap: 8, paddingRight: 12 },
  storeMapFilterButton: { minHeight: 44, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, borderRadius: 22, borderWidth: 1, borderColor: "#D6DDDA", backgroundColor: C.white, paddingHorizontal: 15, shadowColor: "#10281F", shadowOpacity: 0.08, shadowRadius: 8, shadowOffset: { width: 0, height: 3 }, elevation: 3 },
  storeMapFilterButtonActive: { borderColor: C.primary, backgroundColor: C.primaryGhost },
  storeMapFilterText: { color: C.text, fontSize: 13, fontFamily: F.bold },
  storeMapMarker: { minWidth: 46, height: 46, borderRadius: 23, borderWidth: 3, borderColor: C.white, backgroundColor: C.primaryDeep, alignItems: "center", justifyContent: "center", paddingHorizontal: 7, shadowColor: "#000", shadowOpacity: 0.2, shadowRadius: 5, shadowOffset: { width: 0, height: 3 }, elevation: 6 },
  storeMapMarkerWrap: { alignItems: "center", justifyContent: "center" },
  storeMapMarkerActive: { minWidth: 54, height: 54, borderRadius: 27, borderColor: C.primaryDeep, backgroundColor: C.white },
  storeMapMarkerWithLogo: { overflow: "hidden", backgroundColor: C.white, paddingHorizontal: 4 },
  storeMapMarkerImage: { width: "100%", height: "100%" },
  storeMapMarkerText: { color: C.white, fontSize: 13, fontFamily: F.extraBold },
  storeMapMarkerTextActive: { color: C.primaryDeep, fontSize: 15 },
  storeMapClusterMarker: { minWidth: 48, height: 48, borderRadius: 24, borderWidth: 3, borderColor: C.white, backgroundColor: C.primaryDeep, alignItems: "center", justifyContent: "center", paddingHorizontal: 8, shadowColor: "#000", shadowOpacity: 0.2, shadowRadius: 5, shadowOffset: { width: 0, height: 3 }, elevation: 6 },
  storeMapClusterMarkerFavorite: { borderColor: C.primary },
  storeMapClusterMarkerText: { color: C.white, fontSize: 17, fontFamily: F.extraBold },
  storeMapMarkerFavoriteBadge: { position: "absolute", top: -5, right: -5, width: 19, height: 19, borderRadius: 10, borderWidth: 2, borderColor: C.white, backgroundColor: C.primaryDeep, alignItems: "center", justifyContent: "center" },
  storeMapBottomSheet: { position: "absolute", zIndex: 6, left: 0, right: 0, borderTopLeftRadius: 26, borderTopRightRadius: 26, backgroundColor: C.white, paddingHorizontal: 16, paddingTop: 8, paddingBottom: 14, shadowColor: "#10281F", shadowOpacity: 0.16, shadowRadius: 18, shadowOffset: { width: 0, height: -5 }, elevation: 12 },
  storeMapSheetHandle: { alignSelf: "center", width: 42, height: 4, borderRadius: 2, backgroundColor: "#CAD4D0", marginBottom: 9 },
  storeMapSheetHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, marginBottom: 10 },
  storeMapSheetHeaderCopy: { flex: 1, minWidth: 0 },
  storeMapSheetTitle: { color: C.text, fontSize: 18, fontFamily: F.extraBold },
  storeMapSheetSubtitle: { marginTop: 2, color: C.textMuted, fontSize: 11, lineHeight: 16, fontFamily: F.regular },
  storeMapScopeNotice: { color: C.textSoft, fontFamily: F.semibold },
  storeMapModeButton: { minWidth: 82, minHeight: 44, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, borderRadius: 22, backgroundColor: C.primaryDeep, paddingHorizontal: 14 },
  storeMapModeButtonText: { color: C.white, fontSize: 14, fontFamily: F.extraBold },
  storeMapMessage: { color: "#A83939", fontSize: 11, lineHeight: 16, fontFamily: F.semibold, marginBottom: 8 },
});
