[functions.back-office-flyer]
verify_jwt = true

[functions.food-scan]
verify_jwt = false

[functions.send-sale-alert-push]
verify_jwt = false

[functions.sync-sale-alerts]
verify_jwt = false

[functions.delete-account]
verify_jwt = true

[functions.delete-account-request]
verify_jwt = false
