import { StyleSheet } from "react-native";
import { marketingPalette as C } from "../../../shared/design/palette";
export const rs = StyleSheet.create({
  stack: { gap: 16 },
  row: { flexDirection: "row", alignItems: "center", gap: 10 },
  between: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  flex: { flex: 1, minWidth: 0 },
  card: { backgroundColor: C.white, borderRadius: 20, padding: 18, gap: 14 },
  title: { color: C.text, fontSize: 21, fontWeight: "800" },
  text: { color: C.text, fontSize: 16, fontWeight: "600" },
  muted: { color: C.textMuted, fontSize: 13, lineHeight: 20 },
  label: { color: C.textSoft, fontSize: 12, fontWeight: "700" },
  amount: { color: C.primaryDeep, fontSize: 36, fontWeight: "800", letterSpacing: -1 },
  period: {
    flexDirection: "row",
    padding: 4,
    borderRadius: 14,
    backgroundColor: "#E8EFE9",
    gap: 4,
  },
  segment: { flex: 1, paddingVertical: 11, borderRadius: 11, alignItems: "center" },
  selected: { backgroundColor: C.white },
  selectedText: { color: C.primaryDeep, fontWeight: "800" },
  button: {
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.primaryDeep,
  },
  buttonText: { color: C.white, fontWeight: "800", fontSize: 15 },
  secondary: { backgroundColor: C.primaryGhost },
  secondaryText: { color: C.primaryDeep },
  disabled: { opacity: 0.5 },
  icon: {
    minWidth: 44,
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: C.primaryGhost,
  },
  input: {
    borderWidth: 1,
    borderColor: "#CCDAD0",
    backgroundColor: C.white,
    borderRadius: 10,
    minHeight: 46,
    padding: 10,
    color: C.text,
    fontSize: 16,
  },
  field: { flex: 1, gap: 6 },
  divider: { height: 1, backgroundColor: "#E6EDE8" },
  photo: { width: "100%", height: 330, borderRadius: 16, backgroundColor: "#E8EFE9" },
  camera: {
    width: "100%",
    height: 430,
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: C.dark,
  },
  warning: { padding: 14, borderRadius: 12, backgroundColor: "#FFF4DB", gap: 8 },
  error: { color: "#9A3029", fontSize: 14, lineHeight: 21 },
  check: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 12,
    minHeight: 48,
  },
  checkBox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: C.primaryDeep,
    alignItems: "center",
    justifyContent: "center",
  },
  badge: { padding: 12, borderRadius: 14, backgroundColor: C.primaryGhost },
  receiptRow: { flexDirection: "row", alignItems: "center", gap: 12, paddingVertical: 14 },
  search: { borderRadius: 14, backgroundColor: C.white, padding: 14, fontSize: 16, color: C.text },
  modal: { flex: 1, backgroundColor: C.bg },
  modalContent: { padding: 20, gap: 16, paddingBottom: 40 },
  barTrack: { height: 8, borderRadius: 4, backgroundColor: C.primaryGhost, overflow: "hidden" },
  bar: { height: 8, borderRadius: 4, backgroundColor: C.primary },
});
