import { StyleSheet } from "react-native";
import { marketingPalette as C } from "../shared/design/palette";

export const F = {
  regular: "Nunito_400Regular",
  semibold: "Nunito_600SemiBold",
  bold: "Nunito_700Bold",
  extraBold: "Nunito_800ExtraBold",
} as const;

export const st = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: C.bg,
  },
  topBar: {
    minHeight: 68,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: C.line,
    backgroundColor: C.glass,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  brand: {
    color: C.text,
    fontSize: 20,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  alphaPill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  alphaText: {
    color: C.primaryDeep,
    fontSize: 12,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 18,
  },
  sectionStack: {
    gap: 12,
  },
  sectionTitle: {
    color: C.text,
    fontSize: 24,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  sectionSub: {
    color: C.textSoft,
    fontSize: 14,
    lineHeight: 20,
    fontFamily: F.regular,
  },
  searchCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    paddingHorizontal: 12,
    paddingVertical: 2,
  },
  searchInput: {
    height: 46,
    color: C.text,
    fontSize: 14,
    fontFamily: F.semibold,
  },
  categoryRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  categoryChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  categoryChipActive: {
    backgroundColor: C.primaryGhost,
    borderColor: C.primary,
  },
  categoryChipText: {
    color: C.textMuted,
    fontSize: 12,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  categoryChipTextActive: {
    color: C.primaryDeep,
  },
  summaryPanel: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    paddingHorizontal: 14,
    paddingVertical: 4,
  },
  summaryRow: {
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  summaryRowDivider: {
    borderBottomWidth: 1,
    borderBottomColor: C.line,
  },
  summaryLabel: {
    color: C.textSoft,
    fontSize: 14,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  summaryValue: {
    color: C.primaryDeep,
    fontSize: 20,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  rowCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    padding: 14,
    gap: 6,
  },
  rowCardActive: {
    borderColor: C.primary,
    backgroundColor: C.primaryGhost,
  },
  productRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  productMain: {
    flex: 1,
    gap: 4,
  },
  productThumb: {
    width: 72,
    height: 72,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
  },
  productThumbImage: {
    width: "100%",
    height: "100%",
  },
  productThumbPlaceholder: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.primaryGhost,
  },
  productThumbPlaceholderText: {
    color: C.primaryDeep,
    fontSize: 12,
    fontWeight: "800",
    fontFamily: F.extraBold,
    letterSpacing: 0.6,
  },
  detailActionRow: {
    flexDirection: "row",
    gap: 8,
  },
  detailActionBtn: {
    flex: 1,
  },
  chartWrap: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    padding: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  chartMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  chartMetaText: {
    color: C.textMuted,
    fontSize: 12,
    fontFamily: F.bold,
  },
  historyTitle: {
    color: C.text,
    fontSize: 14,
    fontWeight: "800",
    fontFamily: F.extraBold,
    marginTop: 4,
  },
  historyRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  historyLabel: {
    color: C.textMuted,
    fontSize: 12,
    fontFamily: F.bold,
  },
  historyPrice: {
    color: C.text,
    fontSize: 13,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  historyDiff: {
    fontSize: 12,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  historyDiffUp: {
    color: "#A83939",
  },
  historyDiffDown: {
    color: C.primaryDeep,
  },
  watchRowTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  watchRowMain: {
    flex: 1,
    gap: 4,
  },
  removeBtn: {
    minHeight: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#D9A0A0",
    backgroundColor: "#FFF0F0",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  removeBtnDisabled: {
    opacity: 0.6,
  },
  removeBtnText: {
    color: "#A83939",
    fontSize: 12,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  mapCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.line,
    overflow: "hidden",
    backgroundColor: C.white,
  },
  mapView: {
    width: "100%",
    height: 260,
  },
  resultMeta: {
    color: C.textMuted,
    fontSize: 12,
    fontFamily: F.bold,
  },
  adminTitle: {
    color: C.text,
    fontSize: 13,
    fontWeight: "800",
    fontFamily: F.extraBold,
    marginTop: 6,
  },
  formInput: {
    height: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    color: C.text,
    paddingHorizontal: 12,
    fontSize: 14,
    fontFamily: F.semibold,
  },
  itemName: {
    color: C.text,
    fontSize: 16,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  itemMeta: {
    color: C.textSoft,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: F.regular,
  },
  storePrice: {
    color: C.primaryDeep,
    fontSize: 12,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  tagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 4,
  },
  tag: {
    borderRadius: 999,
    backgroundColor: C.primaryGhost,
    color: C.primaryDeep,
    fontSize: 12,
    fontWeight: "700",
    paddingHorizontal: 9,
    paddingVertical: 4,
    fontFamily: F.bold,
  },
  alertTitle: {
    color: C.text,
    fontSize: 15,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  alertTime: {
    color: C.textMuted,
    fontSize: 11,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  authActionRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
  },
  authBtn: {
    minHeight: 42,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  authBtnPrimary: {
    backgroundColor: C.primary,
    borderColor: C.primary,
  },
  authBtnSecondary: {
    backgroundColor: C.white,
    borderColor: C.line,
  },
  authBtnPrimaryText: {
    color: C.white,
    fontSize: 13,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  authBtnSecondaryText: {
    color: C.text,
    fontSize: 13,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  bottomBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: C.line,
    backgroundColor: C.white,
  },
  tabRow: {
    flexDirection: "row",
    gap: 8,
  },
  tabBtn: {
    flex: 1,
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  tabBtnActive: {
    backgroundColor: C.primary,
    borderColor: C.primary,
  },
  tabText: {
    color: C.textMuted,
    fontSize: 11,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  tabTextActive: {
    color: C.white,
    fontFamily: F.bold,
  },
});
