import { StyleSheet } from "react-native";
import { marketingPalette as C } from "../shared/design/palette";

export const F = {
  regular: "Nunito_400Regular",
  semibold: "Nunito_600SemiBold",
  bold: "Nunito_700Bold",
  extraBold: "Nunito_800ExtraBold",
} as const;

export const st = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: C.bg,
  },
  topBar: {
    minHeight: 68,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: C.line,
    backgroundColor: C.glass,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  brand: {
    color: C.text,
    fontSize: 20,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  alphaPill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  alphaText: {
    color: C.primaryDeep,
    fontSize: 12,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 18,
  },
  sectionStack: {
    gap: 12,
  },
  sectionTitle: {
    color: C.text,
    fontSize: 24,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  sectionSub: {
    color: C.textSoft,
    fontSize: 14,
    lineHeight: 20,
    fontFamily: F.regular,
  },
  badge: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: C.primary,
    backgroundColor: C.primaryGhost,
    color: C.primaryDeep,
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 11,
    fontWeight: "800",
    fontFamily: F.extraBold,
    overflow: "hidden",
  },
  dealHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  dealFilterRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  searchCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    paddingHorizontal: 12,
    paddingVertical: 2,
  },
  dealSearchRow: {
    gap: 8,
  },
  searchAndSortRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  sortOptionsScroll: {
    maxHeight: 38,
  },
  searchInput: {
    height: 46,
    color: C.text,
    fontSize: 14,
    fontFamily: F.semibold,
  },
  categoryRow: {
    flexDirection: "row",
    gap: 8,
  },
  homeSearchCard: {
    flex: 1,
  },
  categoryChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  categoryChipActive: {
    backgroundColor: C.primaryGhost,
    borderColor: C.primary,
  },
  categoryChipText: {
    color: C.textMuted,
    fontSize: 12,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  categoryChipTextActive: {
    color: C.primaryDeep,
  },
  summaryPanel: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    paddingHorizontal: 14,
    paddingVertical: 4,
  },
  summaryRow: {
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  summaryRowWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  summaryCard: {
    minWidth: 108,
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 3,
  },
  summaryRowDivider: {
    borderBottomWidth: 1,
    borderBottomColor: C.line,
  },
  summaryLabel: {
    color: C.textSoft,
    fontSize: 14,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  summaryValue: {
    color: C.primaryDeep,
    fontSize: 20,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  summaryValueSmall: {
    color: C.text,
    fontSize: 14,
  },
  rowCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    padding: 14,
    gap: 6,
  },
  rowCardActive: {
    borderColor: C.primary,
    backgroundColor: C.primaryGhost,
  },
  productRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  productMain: {
    flex: 1,
    gap: 4,
  },
  productThumb: {
    width: 72,
    height: 72,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
  },
  productThumbImage: {
    width: "100%",
    height: "100%",
  },
  productThumbPlaceholder: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.primaryGhost,
  },
  productThumbPlaceholderText: {
    color: C.primaryDeep,
    fontSize: 12,
    fontWeight: "800",
    fontFamily: F.extraBold,
    letterSpacing: 0.6,
  },
  productActionRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 4,
  },
  productActionBtn: {
    minHeight: 32,
    borderRadius: 9,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  productActionPrimary: {
    backgroundColor: C.primary,
    borderColor: C.primary,
  },
  productActionSecondary: {
    backgroundColor: C.white,
    borderColor: C.line,
  },
  productActionPrimaryText: {
    color: C.white,
    fontSize: 12,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  productActionSecondaryText: {
    color: C.text,
    fontSize: 12,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  detailActionRow: {
    flexDirection: "row",
    gap: 8,
  },
  detailActionBtn: {
    flex: 1,
  },
  dealSummaryGrid: {
    flexDirection: "row",
    gap: 10,
  },
  dealSummaryCell: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    padding: 10,
    gap: 4,
  },
  dealValueGood: {
    color: C.primaryDeep,
  },
  dealValueNeutral: {
    color: C.text,
  },
  dealText: {
    color: C.primaryDeep,
    fontSize: 13,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  targetRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  targetInput: {
    flex: 1,
  },
  targetSaveBtn: {
    minWidth: 92,
  },
  bestStoreRow: {
    borderColor: C.primary,
    backgroundColor: C.primaryGhost,
  },
  storeChartCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    padding: 10,
    gap: 10,
  },
  storeChartRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  storeChartLabelWrap: {
    width: 82,
    gap: 2,
  },
  storeChartLabel: {
    color: C.text,
    fontSize: 11,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  storeChartBest: {
    color: C.primaryDeep,
    fontSize: 10,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  storeChartTrack: {
    flex: 1,
    height: 18,
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.line,
  },
  storeChartBar: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: C.textMuted,
  },
  storeChartBarBest: {
    backgroundColor: C.primary,
  },
  storeChartPrice: {
    minWidth: 54,
    textAlign: "right",
    color: C.text,
    fontSize: 11,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  chartWrap: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    padding: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  chartMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  chartMetaText: {
    color: C.textMuted,
    fontSize: 12,
    fontFamily: F.bold,
  },
  historyTitle: {
    color: C.text,
    fontSize: 14,
    fontWeight: "800",
    fontFamily: F.extraBold,
    marginTop: 4,
  },
  historyRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  storeRowRight: {
    alignItems: "flex-end",
    gap: 2,
  },
  historyLabel: {
    color: C.textMuted,
    fontSize: 12,
    fontFamily: F.bold,
  },
  historyPrice: {
    color: C.text,
    fontSize: 13,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  historyDiff: {
    fontSize: 12,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  historyDiffUp: {
    color: "#A83939",
  },
  historyDiffDown: {
    color: C.primaryDeep,
  },
  watchRowTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  watchRowMain: {
    flex: 1,
    gap: 4,
  },
  removeBtn: {
    minHeight: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#D9A0A0",
    backgroundColor: "#FFF0F0",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  removeBtnDisabled: {
    opacity: 0.6,
  },
  removeBtnText: {
    color: "#A83939",
    fontSize: 12,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  mapCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.line,
    overflow: "hidden",
    backgroundColor: C.white,
  },
  mapView: {
    width: "100%",
    height: 260,
  },
  storeActionRow: {
    marginTop: 6,
    alignSelf: "stretch",
    alignItems: "flex-start",
  },
  storeActionBtn: {
    minHeight: 34,
    minWidth: 108,
    borderRadius: 8,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
  },
  resultMeta: {
    color: C.textMuted,
    fontSize: 12,
    fontFamily: F.bold,
  },
  formInput: {
    height: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    color: C.text,
    paddingHorizontal: 12,
    fontSize: 14,
    fontFamily: F.semibold,
  },
  itemName: {
    color: C.text,
    fontSize: 16,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  itemMeta: {
    color: C.textSoft,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: F.regular,
  },
  storePrice: {
    color: C.primaryDeep,
    fontSize: 12,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  tagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 4,
  },
  tag: {
    borderRadius: 999,
    backgroundColor: C.primaryGhost,
    color: C.primaryDeep,
    fontSize: 12,
    fontWeight: "700",
    paddingHorizontal: 9,
    paddingVertical: 4,
    fontFamily: F.bold,
  },
  alertTitle: {
    color: C.text,
    fontSize: 15,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  alertTime: {
    color: C.textMuted,
    fontSize: 11,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  authActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  legalLinkRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 6,
  },
  legalActionBtn: {
    minWidth: 116,
  },
  authModeRow: {
    flexDirection: "row",
    gap: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    padding: 4,
  },
  authModeBtn: {
    flex: 1,
    minHeight: 36,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
  },
  authModeBtnActive: {
    backgroundColor: C.primary,
  },
  authModeText: {
    color: C.textMuted,
    fontSize: 12,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  authModeTextActive: {
    color: C.white,
  },
  authBtn: {
    minHeight: 42,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  authBtnPrimary: {
    backgroundColor: C.primary,
    borderColor: C.primary,
  },
  authBtnDanger: {
    backgroundColor: "#A83939",
    borderColor: "#A83939",
  },
  authBtnSecondary: {
    backgroundColor: C.white,
    borderColor: C.line,
  },
  authBtnPrimaryText: {
    color: C.white,
    fontSize: 13,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  authBtnSecondaryText: {
    color: C.text,
    fontSize: 13,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  authBtnDangerText: {
    color: C.white,
    fontSize: 13,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  destructiveWarning: {
    color: "#A83939",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  bottomBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: C.line,
    backgroundColor: C.white,
  },
  tabRow: {
    flexDirection: "row",
    gap: 8,
  },
  tabBtn: {
    flex: 1,
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  tabBtnActive: {
    backgroundColor: C.primary,
    borderColor: C.primary,
  },
  tabBtnContent: {
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
  },
  tabIcon: {
    fontSize: 14,
  },
  tabText: {
    color: C.textMuted,
    fontSize: 11,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  tabTextActive: {
    color: C.white,
    fontFamily: F.bold,
  },
  toastWrap: {
    position: "absolute",
    zIndex: 20,
    minHeight: 46,
    borderRadius: 999,
    backgroundColor: C.text,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    shadowColor: "#000",
    shadowOpacity: 0.16,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  toastText: {
    color: C.white,
    fontSize: 13,
    fontWeight: "800",
    fontFamily: F.extraBold,
    textAlign: "center",
  },

  dealSectionCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    padding: 12,
    gap: 10,
    marginTop: 2,
  },
  dealFeedList: {
    gap: 8,
  },
  dealFeedGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  dealFeedItem: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    padding: 10,
    gap: 10,
    flexDirection: "row",
    alignItems: "stretch",
  },
  dealFeedItemActive: {
    borderColor: C.primary,
    backgroundColor: C.primaryGhost,
  },
  dealFeedThumb: {
    width: 74,
    height: 74,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
  },
  dealFeedThumbPlaceholder: {
    width: 74,
    height: 74,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.primaryGhost,
    alignItems: "center",
    justifyContent: "center",
  },
  dealFeedMain: {
    flex: 1,
    gap: 3,
  },
  dealFeedAction: {
    justifyContent: "flex-end",
    minWidth: 66,
    alignItems: "center",
  },
  dealSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  inlinePill: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: C.primary,
    backgroundColor: C.primaryGhost,
  },
  sortPill: {
    borderColor: C.line,
    backgroundColor: C.white,
  },
  sortPillActive: {
    borderColor: C.primary,
    backgroundColor: C.primaryGhost,
  },
  sortPillTextActive: {
    color: C.primaryDeep,
  },
  inlinePillDisabled: {
    borderColor: C.line,
    backgroundColor: C.bg,
  },
  inlinePillText: {
    color: C.primaryDeep,
    fontSize: 11,
    fontWeight: "800",
    fontFamily: F.bold,
  },
  inlinePillTextDisabled: {
    color: C.textMuted,
  },
  sortOptionsWrap: {
    flexDirection: "row",
    gap: 8,
  },
  dealSectionScroll: {
    gap: 10,
    paddingRight: 6,
  },
  dealCard: {
    width: "48.5%",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.bg,
    overflow: "hidden",
  },
  dealCardActive: {
    borderColor: C.primary,
  },
  dealCardImage: {
    width: "100%",
    height: 112,
    backgroundColor: C.primaryPale,
  },
  dealCardImagePlaceholder: {
    width: "100%",
    height: 112,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.primaryPale,
  },
  dealCardBody: {
    padding: 10,
    gap: 4,
  },
  dealCardBottomRow: {
    marginTop: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  dealPrice: {
    color: C.textSoft,
    fontSize: 11,
    fontWeight: "700",
    fontFamily: F.bold,
  },
  priceJudgmentGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  priceJudgmentCell: {
    width: "48%",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    padding: 10,
    backgroundColor: C.bg,
    gap: 4,
  },
  watchTargetSummary: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    padding: 8,
    gap: 8,
  },
  targetBadge: {
    backgroundColor: C.primaryGhost,
  },
  progressTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: "#EAF3D2",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: C.line,
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: C.primary,
  },
  onboardingBackdrop: {
    position: "absolute",
    inset: 0,
    backgroundColor: "rgba(11, 15, 4, 0.44)",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  onboardingCard: {
    width: "100%",
    maxWidth: 390,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.white,
    padding: 16,
    gap: 8,
  },
  onboardingTitle: {
    color: C.text,
    fontSize: 20,
    fontWeight: "800",
    fontFamily: F.extraBold,
  },
  onboardingMeta: {
    color: C.textSoft,
    fontSize: 13,
    lineHeight: 20,
    fontFamily: F.regular,
  },
  onboardingBtn: {
    minHeight: 42,
    marginTop: 4,
  },
  inlineToggleBtn: {
    minHeight: 40,
    marginTop: 4,
    marginBottom: 4,
  },
});
