import { Platform } from "react-native";
import P from "../constants/palette";

export const heroStyles = {
  heroWrap: {
    backgroundColor: P.bg,
    paddingTop: 92,
    paddingBottom: 108,
    overflow: "hidden",
  },
  heroContent: {
    gap: 72,
  },
  heroCopy: {
    gap: 18,
  },
  heroPillRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  heroPill: {
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: "rgba(97,227,146,0.35)",
    backgroundColor: "rgba(97,227,146,0.08)",
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  heroPillText: {
    fontSize: 12,
    fontWeight: "700",
    color: P.primaryDeep,
    letterSpacing: 0.4,
  },
  heroTitle: {
    fontSize: 44,
    lineHeight: 49,
    fontWeight: "800",
    color: P.text,
    letterSpacing: -1.6,
  },
  heroSub: {
    fontSize: 18,
    lineHeight: 29,
    color: P.textSoft,
  },

  /* Photo-led grocery story */
  heroCardWrap: {
    width: "100%",
    minHeight: 460,
    position: "relative",
  },
  previewShell: {
    width: "100%",
    minHeight: 510,
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    padding: 22,
    borderWidth: 1,
    borderColor: "rgba(7,31,18,0.12)",
    gap: 18,
    transform: [{ rotate: "-1.2deg" }],
    ...(Platform.OS === "web"
      ? ({ boxShadow: "0 34px 80px rgba(7,31,18,0.15)" } as any)
      : {}),
  },
  previewTopBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  previewKicker: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.8,
    color: P.primary,
  },
  previewHeading: {
    marginTop: 3,
    fontSize: 24,
    lineHeight: 29,
    fontWeight: "800",
    color: P.text,
    letterSpacing: -0.5,
  },
  previewAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: P.dark,
    alignItems: "center",
    justifyContent: "center",
  },
  previewAvatarText: { color: P.white, fontSize: 11, fontWeight: "800" },
  previewSearch: {
    height: 46,
    borderRadius: 14,
    backgroundColor: "#F2F5F3",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  previewSearchText: { fontSize: 13, color: P.textMuted, fontWeight: "600" },
  previewProductRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 2,
  },
  previewProductVisual: {
    width: 64,
    height: 64,
    borderRadius: 18,
    backgroundColor: "#FFF0E8",
    alignItems: "center",
    justifyContent: "center",
  },
  previewProductGlyph: { alignItems: "center", justifyContent: "center" },
  previewProductCopy: { flex: 1, gap: 2 },
  previewProductMeta: { fontSize: 9, letterSpacing: 1.1, color: P.textMuted, fontWeight: "800" },
  previewProductName: { fontSize: 17, color: P.text, fontWeight: "800" },
  previewProductUnit: { fontSize: 12, color: P.textMuted, fontWeight: "600" },
  previewLiveBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: P.primaryGhost,
  },
  previewLiveDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: P.primary },
  previewLiveText: { fontSize: 9, letterSpacing: 0.8, color: P.primaryDeep, fontWeight: "800" },
  previewPriceList: { gap: 8 },
  previewPriceRow: {
    minHeight: 54,
    borderRadius: 15,
    backgroundColor: "#F7F9F8",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    gap: 10,
    borderWidth: 1,
    borderColor: "transparent",
  },
  previewPriceRowBest: { backgroundColor: P.primaryGhost, borderColor: P.line },
  previewStoreMark: {
    width: 30,
    height: 30,
    borderRadius: 10,
    backgroundColor: P.white,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(7,31,18,0.08)",
  },
  previewStoreMarkText: { color: P.primaryDeep, fontSize: 12, fontWeight: "800" },
  previewStoreName: { flex: 1, color: P.text, fontSize: 13, fontWeight: "700" },
  previewDelta: { color: P.primary, fontSize: 11, fontWeight: "800" },
  previewPrice: { minWidth: 54, textAlign: "right", color: P.text, fontSize: 15, fontWeight: "800" },
  previewSavingBar: {
    marginTop: "auto",
    minHeight: 52,
    borderRadius: 16,
    backgroundColor: "#CFF36B",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    gap: 10,
  },
  previewSavingIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.65)",
    alignItems: "center",
    justifyContent: "center",
  },
  previewSavingText: { flex: 1, color: P.dark, fontSize: 13, fontWeight: "800" },
} as const;
