// Disposable PostgreSQL-compatible DB; never connects to the hosted project.
import assert from "node:assert/strict";
import { loadRelease, migrationTransaction, sha256 } from "../../scripts/supabase-release-lib.mjs";
import { featureChecks } from "../../scripts/supabase-release-checks.mjs";
const { PGlite } = await import(process.env.PGLITE_MODULE ?? "@electric-sql/pglite");
const db = new PGlite();
await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE SCHEMA auth; CREATE SCHEMA storage;
CREATE TABLE auth.users(id uuid primary key);
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$SELECT NULL::uuid$$;
CREATE TABLE storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
CREATE TABLE storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
GRANT USAGE ON SCHEMA auth,storage TO authenticated,anon;
GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated,anon;
GRANT SELECT,INSERT,UPDATE,DELETE ON storage.objects TO authenticated;`);
const migration = (version, source) => ({ version, name: `${version}_test.sql`, source, hash: sha256(source) });
const a = migration("20261003000001", "create table public.deploy_test(value text); insert into public.deploy_test values ('O''Brien');");
await db.exec(migrationTransaction([a]));
await db.exec(migrationTransaction([a]));
assert.equal((await db.query("select count(*)::int n from public.deploy_test")).rows[0].n, 1);
assert.equal((await db.query("select count(*)::int n from pocketcart_deploy.migrations")).rows[0].n, 1);
const rollback = async (sql) => {
  await assert.rejects(db.exec(sql));
  await db.exec("ROLLBACK;");
};
await rollback(migrationTransaction([{ ...a, hash: "tampered" }]));
assert.equal((await db.query("select count(*)::int n from public.deploy_test")).rows[0].n, 1);
const b = migration("20261003000002", "insert into public.deploy_test values ('must roll back');");
const c = migration("20261003000003", "select * from nonexistent_table;");
await rollback(migrationTransaction([b, c]));
assert.equal((await db.query("select count(*)::int n from public.deploy_test")).rows[0].n, 1);
assert.equal((await db.query("select count(*)::int n from pocketcart_deploy.migrations")).rows[0].n, 1);
await rollback(migrationTransaction([b], { checks: ["DO $$ BEGIN RAISE EXCEPTION 'permission check failed'; END $$;"] }));
assert.equal((await db.query("select count(*)::int n from public.deploy_test")).rows[0].n, 1);
await db.exec(migrationTransaction([b], { recordExisting: true }));
assert.equal((await db.query("select count(*)::int n from public.deploy_test")).rows[0].n, 1);
await db.exec(migrationTransaction([b])); // recorded existing SQL is not replayed
assert.equal((await db.query("select count(*)::int n from public.deploy_test")).rows[0].n, 1);
await db.exec("SET ROLE authenticated;");
await assert.rejects(db.query("select * from pocketcart_deploy.migrations"), /permission denied/);
await db.exec("RESET ROLE;");
const release = await loadRelease(new URL("../../", import.meta.url).pathname);
const receipts = release.migrations.filter((item) => item.version === "20260916010000");
await db.exec(migrationTransaction(receipts, { checks: featureChecks(receipts) }));
await db.exec(migrationTransaction(receipts, { checks: featureChecks(receipts) }));
assert.equal((await db.query("select count(*)::int n from pocketcart_deploy.migrations where version='20260916010000'")).rows[0].n, 1);
await db.exec(`CREATE TABLE public.profiles(id uuid PRIMARY KEY REFERENCES auth.users(id),full_name text);
CREATE TABLE public.products(id uuid PRIMARY KEY);
CREATE TABLE public.admin_users(user_id uuid PRIMARY KEY);
CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$SELECT nullif(current_setting('app.uid',true),'')::uuid$$;
CREATE FUNCTION public.is_admin() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public
AS $$SELECT EXISTS(SELECT 1 FROM public.admin_users WHERE user_id=auth.uid())$$;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;
INSERT INTO storage.buckets(id,name,public) VALUES('product-images','product-images',true);`);
const setup = release.migrations.filter((item) => ["20260822170000", "20260914010000", "20260914020000", "20260914030000", "20260914040000", "20260914050000", "20260914060000"].includes(item.version));
await db.exec(migrationTransaction(setup, { checks: featureChecks(setup) }));
await db.exec("GRANT ALL ON public.freezer_items TO authenticated;");
const fix = release.migrations.filter((item) => item.version === "20261003010000");
await db.exec(migrationTransaction(fix));
await db.exec(migrationTransaction(fix));
const uid = (n) => `10000000-0000-0000-0000-${String(n).padStart(12, "0")}`;
await db.query("INSERT INTO auth.users VALUES($1),($2)", [uid(1),uid(2)]);
await db.query("INSERT INTO public.admin_users VALUES($1)", [uid(1)]);
const as = async (n) => {
  await db.exec("RESET ROLE;");
  await db.query("SELECT set_config('app.uid',$1,false)", [uid(n)]);
  await db.exec("SET ROLE authenticated;");
};
await as(1);
const image = (await db.query("INSERT INTO storage.objects(bucket_id,name) VALUES('product-images','admin-test.jpg') RETURNING id")).rows[0].id;
await db.query("UPDATE storage.objects SET name='admin-updated.jpg' WHERE id=$1", [image]);
await as(2);
await assert.rejects(db.query("INSERT INTO storage.objects(bucket_id,name) VALUES('product-images','ordinary-test.jpg')"), /row-level security/);
assert.equal((await db.query("SELECT id FROM storage.objects WHERE bucket_id='product-images'")).rows.length, 0);
assert.equal((await db.query("UPDATE storage.objects SET name='forged.jpg' WHERE id=$1 RETURNING id", [image])).rows.length, 0);
assert.equal((await db.query("DELETE FROM storage.objects WHERE id=$1 RETURNING id", [image])).rows.length, 0);
await db.query("INSERT INTO public.freezer_items(user_id,name) VALUES($1,'Private food')", [uid(2)]);
await as(1);
assert.equal((await db.query("SELECT id FROM public.freezer_items")).rows.length, 0);
assert.equal((await db.query("DELETE FROM storage.objects WHERE id=$1 RETURNING id", [image])).rows.length, 1);
await db.exec(`RESET ROLE;
CREATE TABLE public.stores(latitude numeric,longitude numeric);
INSERT INTO public.stores VALUES(91,0);
ALTER TABLE public.stores ADD CONSTRAINT stores_latitude_range CHECK(latitude >= -90 AND latitude <= 90) NOT VALID;
ALTER TABLE public.stores ADD CONSTRAINT stores_longitude_range CHECK(longitude >= -180 AND longitude <= 180) NOT VALID;
ALTER TABLE public.products ADD COLUMN gtin text;
ALTER TABLE public.products ADD CONSTRAINT products_gtin_format_check CHECK(gtin IS NULL OR gtin ~ '^[0-9]{13}$') NOT VALID;`);
const validation = release.migrations.filter((item) => item.version === "20261003020000");
await rollback(migrationTransaction(validation));
assert.equal((await db.query("SELECT latitude FROM public.stores")).rows[0].latitude, "91");
assert.equal((await db.query("SELECT count(*)::int n FROM pocketcart_deploy.migrations WHERE version='20261003020000'")).rows[0].n, 0);
await db.exec("UPDATE public.stores SET latitude=49;");
await db.exec(migrationTransaction(validation));
await db.exec(migrationTransaction(validation));
assert.equal((await db.query("SELECT count(*)::int n FROM pg_constraint WHERE conname IN ('stores_latitude_range','stores_longitude_range','products_gtin_format_check') AND NOT convalidated")).rows[0].n, 0);
await db.close();
console.log("Backend runner DB passed: SQL quoting, exact-once retry, hash refusal, batch/check rollback, record-only adoption, private history, real receipt/family/storage migrations, admin image CRUD/non-admin denial, catalog validation and refusal without data changes.");
