export const marketingCopy = {
  en: {
    eyebrow: "A LITTLE PLANNING. A BETTER GROCERY RUN.",
    title: "Good groceries.",
    accent: "Better prices.",
    intro:
      "Know what to buy, where to buy it, and when it’s a good deal. Your next grocery run starts here.",
    explore: "Explore PocketCart",
    how: "See how it works",
    platform: "Made for iOS & Android",
    note: "Browse prices without an account",
    preview: "PRODUCT PREVIEW · EXAMPLE PRICES",
    basket: "Fresh picks. Thoughtful spending.",
    appTitle: "Your next grocery run",
    search: "Search your everyday essentials",
    produce: "Fresh produce",
    product: "Roma tomatoes",
    unit: "1 lb",
    current: "Lowest listed price",
    previous: "Last sale",
    sale: "Lower than last sale",
    add: "Add to list",
    added: "Added to your list",
    remove: "Remove from list",
    list: "Shopping list",
    alert: "Sale alerts",
    alertBody: "Keep an eye on your everyday favourites.",
    featureEyebrow: "LESS GUESSWORK. MORE GOOD FINDS.",
    featureTitle: "Everything for your next trip.",
    featureIntro: "From the first price check to the last item on your list.",
    compare: "A better price, in perspective.",
    compareBody:
      "Compare listed store prices and look back at previous sales. Decide with a little more context.",
    compareLabel: "COMPARE STORE PRICES",
    example: "Illustrative preview. Prices and stores are examples.",
    best: "Lowest",
    stores: ["Store A", "Store B", "Store C"],
    listTitle: "A list that goes with you.",
    listBody: "Turn a good find into a plan. Keep your essentials together for your next trip.",
    listItems: ["Roma tomatoes", "Milk", "Sourdough bread"],
    listHint: "Your list, ready when you are.",
    alertTitle: "Your favourites. On your radar.",
    alertDescription: "Save products to your watchlist and follow their next sale.",
    alertSample: "A little heads-up for your next shop.",
    howEyebrow: "FROM A GOOD FIND TO YOUR BASKET",
    howTitle: "One product. Three simple steps.",
    steps: [
      {
        title: "Find your essentials",
        body: "Search a product or explore the current sale selection.",
      },
      {
        title: "See the difference",
        body: "Compare listed prices and check previous sale periods.",
      },
      {
        title: "Make it a plan",
        body: "Add it to your shopping list or save it for a future sale.",
      },
    ],
    searchExample: "Roma tomatoes",
    compareExample: "$2.49 → $1.99",
    listExample: "Roma tomatoes · 1 lb",
    ctaEyebrow: "A FRESH APPROACH TO EVERYDAY SHOPPING",
    ctaTitle: "Make room for better finds.",
    ctaBody:
      "Price comparisons, a thoughtful list, and your favourite groceries. Together in PocketCart.",
    ctaStatus: "Store links coming soon",
    ios: "iOS app",
    android: "Android app",
    available: "In preparation",
  },
  fr: {
    eyebrow: "UN PEU DE PRÉPARATION. DE MEILLEURES COURSES.",
    title: "De bons produits.",
    accent: "Au bon prix.",
    intro:
      "Sachez quoi acheter, où l’acheter et quand profiter d’un bon prix. Vos prochaines courses commencent ici.",
    explore: "Découvrir PocketCart",
    how: "Comment ça marche",
    platform: "Pensé pour iOS et Android",
    note: "Consultez les prix sans compte",
    preview: "APERÇU DU PRODUIT · PRIX D’EXEMPLE",
    basket: "Des produits frais. Des achats réfléchis.",
    appTitle: "Vos prochaines courses",
    search: "Rechercher vos essentiels",
    produce: "Fruits et légumes",
    product: "Tomates Roma",
    unit: "1 lb",
    current: "Prix affiché le plus bas",
    previous: "Dernière promotion",
    sale: "Moins cher que la dernière promotion",
    add: "Ajouter à la liste",
    added: "Ajouté à votre liste",
    remove: "Retirer de la liste",
    list: "Liste de courses",
    alert: "Alertes de promotion",
    alertBody: "Gardez un œil sur vos produits préférés.",
    featureEyebrow: "MOINS D’HÉSITATIONS. PLUS DE TROUVAILLES.",
    featureTitle: "Tout pour vos prochaines courses.",
    featureIntro: "Du premier prix consulté au dernier article de votre liste.",
    compare: "Un meilleur prix, en perspective.",
    compareBody:
      "Comparez les prix affichés et les promotions précédentes. Décidez avec un peu plus de contexte.",
    compareLabel: "COMPARER LES PRIX",
    example: "Aperçu illustratif. Prix et magasins donnés à titre d’exemple.",
    best: "Le plus bas",
    stores: ["Magasin A", "Magasin B", "Magasin C"],
    listTitle: "Une liste qui vous suit.",
    listBody:
      "Transformez une bonne trouvaille en plan. Regroupez vos essentiels pour votre prochaine visite.",
    listItems: ["Tomates Roma", "Lait", "Pain au levain"],
    listHint: "Votre liste, prête à vous suivre.",
    alertTitle: "Vos favoris. À portée de main.",
    alertDescription: "Enregistrez des produits et suivez leur prochaine promotion.",
    alertSample: "Un petit rappel pour vos prochaines courses.",
    howEyebrow: "D’UNE BONNE TROUVAILLE À VOTRE PANIER",
    howTitle: "Un produit. Trois étapes simples.",
    steps: [
      {
        title: "Trouvez vos essentiels",
        body: "Recherchez un produit ou explorez les promotions en cours.",
      },
      {
        title: "Voyez la différence",
        body: "Comparez les prix affichés et les promotions précédentes.",
      },
      {
        title: "Préparez vos courses",
        body: "Ajoutez le produit à votre liste ou suivez une prochaine promotion.",
      },
    ],
    searchExample: "Tomates Roma",
    compareExample: "2,49 $ → 1,99 $",
    listExample: "Tomates Roma · 1 lb",
    ctaEyebrow: "UN REGARD NEUF SUR LES COURSES",
    ctaTitle: "Faites place aux bonnes trouvailles.",
    ctaBody:
      "Des prix comparés, une liste bien pensée et vos produits préférés. Réunis dans PocketCart.",
    ctaStatus: "Liens de téléchargement à venir",
    ios: "App iOS",
    android: "App Android",
    available: "En préparation",
  },
};
