import { marketingPalette as C } from "../../shared/design/palette";

export const adminDataStyles = {
  statGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  statCard: {
    minWidth: 140,
    flexGrow: 1,
    borderRadius: 12,
    borderWidth: 0,
    backgroundColor: "#f8faff",
    paddingHorizontal: 10,
    paddingVertical: 7,
    gap: 1,
  },
  statLabel: {
    color: "#748096",
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  statValue: {
    color: "#2b313d",
    fontSize: 22,
    lineHeight: 24,
    fontWeight: "800",
  },
  statHint: {
    color: "#6f7b8f",
    fontSize: 10,
    lineHeight: 12,
  },
  panelTitle: {
    color: "#2d3444",
    fontSize: 28,
    fontWeight: "800",
    marginTop: 2,
  },
  dualColumnGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  productAdminStack: {
    gap: 12,
  },
  dataCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#d8dee8",
    backgroundColor: "#ffffff",
    padding: 14,
    gap: 8,
    minWidth: 280,
    flexGrow: 1,
  },
  flyerPanel: {
    borderWidth: 1,
    borderColor: "#d3d9e4",
    backgroundColor: "#ffffff",
    minWidth: 280,
  },
  flyerToolbarBtn: {
    minHeight: 27,
    borderRadius: 3,
    borderColor: "#cdd4df",
    backgroundColor: "#e9edf3",
    paddingHorizontal: 13,
  },
  flyerToolbarBtnText: {
    color: "#455266",
    fontSize: 11,
    fontWeight: "700",
  },
  emptyStateCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e1e7f0",
    backgroundColor: "#f8fafc",
    padding: 16,
    gap: 6,
  },
  flyerTable: {
    borderWidth: 1,
    borderColor: "#cfd7e3",
    borderRadius: 0,
    overflow: "hidden",
    alignSelf: "flex-start",
    margin: 8,
  },
  flyerTableRow: {
    flexDirection: "row",
    alignItems: "stretch",
    minHeight: 32,
  },
  flyerTableRowSelected: {
    backgroundColor: "#cfe1ff",
  },
  flyerTableHeader: {
    backgroundColor: "#eef1f5",
  },
  flyerTableEmptyRow: {
    width: 1800,
    minHeight: 36,
    borderTopWidth: 1,
    borderTopColor: "#d9dee8",
    backgroundColor: "#ffffff",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  flyerHeaderCell: {
    borderRightWidth: 1,
    borderRightColor: "#d5dce7",
    color: "#4c5869",
    fontSize: 10,
    fontWeight: "800",
    paddingHorizontal: 7,
    paddingVertical: 7,
    textTransform: "uppercase",
  },
  flyerInputCell: {
    minHeight: 32,
    borderRadius: 0,
    borderWidth: 0,
    borderRightWidth: 1,
    borderRightColor: "#dbe1ea",
    borderTopWidth: 1,
    borderTopColor: "#e3e8f0",
    backgroundColor: "#ffffff",
    color: "#293346",
    paddingHorizontal: 7,
    fontSize: 11,
  },
  flyerInputCellSelected: {
    backgroundColor: "#cfe1ff",
  },
  flyerSelectCell: {
    width: 68,
    minHeight: 32,
    borderRightWidth: 1,
    borderRightColor: "#dbe1ea",
    borderTopWidth: 1,
    borderTopColor: "#e3e8f0",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  flyerSelectCellActive: {
    backgroundColor: "#cfe1ff",
  },
  flyerSelectText: {
    color: "#6a768e",
    fontSize: 11,
    fontWeight: "800",
  },
  flyerSelectTextActive: {
    color: C.primaryDeep,
  },
  flyerCellSelect: {
    width: 68,
  },
  flyerCellImage: {
    width: 152,
  },
  flyerImageCell: {
    width: 152,
    minHeight: 82,
    borderRightWidth: 1,
    borderRightColor: "#dbe1ea",
    borderTopWidth: 1,
    borderTopColor: "#e3e8f0",
    backgroundColor: "#ffffff",
    padding: 6,
    gap: 5,
  },
  flyerPreviewImage: {
    width: 138,
    height: 52,
    borderRadius: 4,
    backgroundColor: "#eef2f7",
  },
  flyerPreviewEmpty: {
    width: 138,
    height: 52,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#d8dee8",
    backgroundColor: "#f8fafc",
    alignItems: "center",
    justifyContent: "center",
  },
  flyerImageMeta: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 5,
  },
  flyerImageStatusText: {
    flex: 1,
    color: "#69758a",
    fontSize: 10,
    fontWeight: "700",
  },
  flyerImageToggle: {
    minWidth: 58,
    minHeight: 20,
    borderRadius: 3,
    borderWidth: 1,
    borderColor: "#cdd4df",
    backgroundColor: "#f3f6fa",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 5,
  },
  flyerImageToggleActive: {
    borderColor: "#8fb7ff",
    backgroundColor: "#e5f0ff",
  },
  flyerImageToggleText: {
    color: "#69758a",
    fontSize: 9,
    fontWeight: "800",
  },
  flyerImageToggleTextActive: {
    color: C.primaryDeep,
  },
  flyerCellMart: {
    width: 120,
  },
  flyerCellBranch: {
    width: 140,
  },
  flyerCellDate: {
    width: 116,
  },
  flyerCellName: {
    width: 220,
  },
  flyerCellCategory: {
    width: 120,
  },
  flyerCellBrand: {
    width: 130,
  },
  flyerCellPrice: {
    width: 100,
  },
  flyerCellUnit: {
    width: 90,
  },
  flyerCellMemo: {
    width: 320,
  },
  dataCardWide: {
    minWidth: 520,
    flex: 2,
  },
  dataCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  },
  dataCardTitle: {
    color: "#2f3747",
    fontSize: 20,
    fontWeight: "800",
  },
  dataMuted: {
    color: "#6f7b92",
    fontSize: 12,
    lineHeight: 17,
  },
  dataRow: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e2e7f0",
    backgroundColor: "#fafbfd",
    paddingHorizontal: 11,
    paddingVertical: 9,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  dataRowMain: {
    flex: 1,
    gap: 2,
  },
  dataRowTitle: {
    color: "#323b4d",
    fontSize: 14,
    fontWeight: "700",
  },
  dataMeta: {
    color: "#56617a",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "right",
  },
  auditCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f2",
    backgroundColor: "#f8faff",
    padding: 10,
    gap: 8,
  },
  auditRow: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e2e7f0",
    backgroundColor: "#ffffff",
    paddingHorizontal: 11,
    paddingVertical: 9,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  formRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    alignItems: "center",
  },
  input: {
    minHeight: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#d8dee8",
    backgroundColor: "#f7f9fc",
    color: C.text,
    paddingHorizontal: 12,
    fontSize: 13,
  },
  inputGrow: {
    flexGrow: 1,
    minWidth: 220,
  },
  inputNarrow: {
    minWidth: 150,
    flexGrow: 1,
  },
} as const;
