import { Platform } from "react-native";
import { marketingPalette as C } from "../../shared/design/palette";

export const adminLayoutStyles = {
  root: {
    flex: 1,
    backgroundColor: "#f3f4f7",
    ...(Platform.OS === "web" ? ({ minHeight: "100vh", height: "100vh", width: "100%" } as any) : {}),
  },
  workspace: {
    flex: 1,
    flexDirection: "row",
    gap: 0,
  },
  workspaceStack: {
    flexDirection: "column",
    gap: 12,
  },
  mainPanel: {
    flex: 1,
    minWidth: 0,
    padding: 12,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 56,
    gap: 12,
  },
  scrollContentAuth: {
    flexGrow: 1,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    flexWrap: "wrap",
  },
  pageTitle: {
    color: "#2a2f3a",
    fontSize: 34,
    fontWeight: "800",
    letterSpacing: -0.4,
  },
  pageSub: {
    color: "#677285",
    fontSize: 13,
    marginTop: 3,
  },
  infoCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#d8dee8",
    backgroundColor: "#ffffff",
    padding: 16,
    gap: 6,
  },
  infoTitle: {
    color: "#2f3a52",
    fontSize: 20,
    fontWeight: "800",
  },
  infoBody: {
    color: "#616d83",
    fontSize: 13,
    lineHeight: 19,
  },
  authCard: {
    width: "100%",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#d8dee8",
    backgroundColor: "#ffffff",
    padding: 24,
    gap: 14,
    maxWidth: 460,
    ...(Platform.OS === "web" ? ({ boxShadow: "0 14px 36px rgba(34, 44, 66, 0.08)" } as any) : {}),
  },
  authStage: {
    flexGrow: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 24,
  },
  authField: {
    gap: 6,
  },
  authFieldLabel: {
    color: "#344158",
    fontSize: 13,
    fontWeight: "700",
  },
  authInput: {
    minHeight: 48,
    backgroundColor: "#ffffff",
    fontSize: 15,
  },
  authPasswordField: {
    position: "relative",
  },
  authPasswordInput: {
    paddingRight: 72,
  },
  authPasswordToggle: {
    position: "absolute",
    right: 2,
    top: 2,
    minWidth: 60,
    minHeight: 44,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  authPasswordToggleText: {
    color: C.primaryDeep,
    fontSize: 13,
    fontWeight: "800",
  },
  authSubmitButton: {
    minHeight: 48,
    marginTop: 2,
  },
  noticeCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#d9e1ff",
    backgroundColor: "#eef3ff",
    paddingLeft: 12,
    paddingRight: 4,
    paddingVertical: 4,
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  noticeText: {
    flex: 1,
    color: "#415590",
    fontSize: 13,
    lineHeight: 18,
  },
  noticeDismissButton: {
    width: 36,
    minHeight: 36,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  noticeDismissText: {
    color: "#415590",
    fontSize: 22,
    lineHeight: 24,
    fontWeight: "700",
  },
  mobileMenuRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  mobileMenuBtn: {
    minHeight: 44,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#dde3ee",
    backgroundColor: "#ffffff",
    paddingHorizontal: 11,
    paddingVertical: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  mobileMenuBtnActive: {
    borderColor: C.primaryLight,
    backgroundColor: C.primaryGhost,
  },
  mobileMenuText: {
    color: "#3a465d",
    fontSize: 12,
    fontWeight: "700",
  },
  mobileMenuTextActive: {
    color: C.primaryDeep,
  },
  mobileMenuBadge: {
    minWidth: 22,
    height: 22,
    borderRadius: 999,
    backgroundColor: "#eceff4",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 5,
  },
  mobileMenuBadgeText: {
    color: "#4e5c74",
    fontSize: 10,
    fontWeight: "800",
  },
} as const;
