import { Platform } from "react-native";
import { marketingPalette as C } from "../../shared/design/palette";

export const adminLayoutStyles = {
  root: {
    flex: 1,
    backgroundColor: "#f3f4f7",
    ...(Platform.OS === "web" ? ({ minHeight: "100vh", height: "100vh", width: "100%" } as any) : {}),
  },
  workspace: {
    flex: 1,
    flexDirection: "row",
    gap: 0,
  },
  workspaceStack: {
    flexDirection: "column",
    gap: 12,
  },
  sidebar: {
    width: 280,
    minHeight: 0,
    height: "100%",
    borderRadius: 0,
    borderWidth: 1,
    borderColor: "#d8dee8",
    backgroundColor: "#ffffff",
    padding: 14,
    gap: 14,
    ...(Platform.OS === "web" ? ({ height: "100vh", alignSelf: "stretch" } as any) : {}),
  },
  sidebarMobile: {
    width: "100%",
    minHeight: 0,
    height: "auto",
    borderRadius: 12,
    position: "relative",
    padding: 8,
    gap: 8,
    flexDirection: "row",
    alignItems: "center",
  },
  sidebarHeader: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#dde3ee",
    backgroundColor: "#f5f8ff",
    padding: 12,
    gap: 4,
  },
  sidebarHeaderMobile: {
    flex: 0.9,
    minWidth: 100,
    borderWidth: 0,
    backgroundColor: "transparent",
    padding: 0,
    gap: 0,
  },
  sidebarBrand: {
    color: "#2a3f7f",
    fontSize: 18,
    fontWeight: "800",
  },
  sidebarSub: {
    color: "#5d6a82",
    fontSize: 12,
    lineHeight: 17,
  },
  menuGroup: {
    gap: 8,
  },
  menuBtn: {
    minHeight: 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#dfe4ec",
    backgroundColor: "#ffffff",
    paddingHorizontal: 11,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  menuBtnActive: {
    borderColor: C.primaryLight,
    backgroundColor: C.primaryGhost,
  },
  menuText: {
    color: "#2e3a4f",
    fontSize: 13,
    fontWeight: "700",
  },
  menuTextActive: {
    color: C.primaryDeep,
  },
  menuBadge: {
    minWidth: 24,
    height: 24,
    borderRadius: 999,
    backgroundColor: "#eceff4",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  menuBadgeActive: {
    backgroundColor: C.primaryPale,
  },
  menuBadgeText: {
    color: "#4e5c74",
    fontSize: 11,
    fontWeight: "800",
  },
  menuBadgeTextActive: {
    color: C.primaryDeep,
  },
  sidebarFooter: {
    marginTop: "auto",
    borderTopWidth: 1,
    borderTopColor: "#e5e9f1",
    paddingTop: 12,
    gap: 7,
  },
  sidebarFooterMobile: {
    flex: 0,
    minWidth: 0,
    marginTop: 0,
    borderTopWidth: 0,
    paddingTop: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
  },
  sidebarUserBlock: {
    flex: 1,
    minWidth: 0,
  },
  sidebarUser: {
    color: "#2e3748",
    fontSize: 13,
    fontWeight: "700",
  },
  sidebarRole: {
    color: "#7a859a",
    fontSize: 12,
  },
  sidebarCollapsedToggle: {
    width: 54,
    height: 54,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#cfd7ea",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    ...(Platform.OS === "web"
      ? ({ position: "fixed", left: 12, bottom: 12, zIndex: 40, boxShadow: "0 8px 20px rgba(24,34,52,0.18)" } as any)
      : ({ position: "absolute", left: 12, bottom: 12 } as any)),
  },
  sidebarCollapsedToggleIcon: {
    color: C.primaryDeep,
    fontSize: 28,
    fontWeight: "900",
    marginTop: -2,
  },
  mainPanel: {
    flex: 1,
    minWidth: 0,
    padding: 12,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 56,
    gap: 12,
  },
  scrollContentAuth: {
    flexGrow: 1,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    flexWrap: "wrap",
  },
  pageTitle: {
    color: "#2a2f3a",
    fontSize: 34,
    fontWeight: "800",
    letterSpacing: -0.4,
  },
  pageSub: {
    color: "#677285",
    fontSize: 13,
    marginTop: 3,
  },
  infoCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#d8dee8",
    backgroundColor: "#ffffff",
    padding: 16,
    gap: 6,
  },
  infoTitle: {
    color: "#2f3a52",
    fontSize: 20,
    fontWeight: "800",
  },
  infoBody: {
    color: "#616d83",
    fontSize: 13,
    lineHeight: 19,
  },
  authCard: {
    width: "100%",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#d8dee8",
    backgroundColor: "#ffffff",
    padding: 24,
    gap: 14,
    maxWidth: 460,
    ...(Platform.OS === "web" ? ({ boxShadow: "0 14px 36px rgba(34, 44, 66, 0.08)" } as any) : {}),
  },
  authStage: {
    flexGrow: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 24,
  },
  authField: {
    gap: 6,
  },
  authFieldLabel: {
    color: "#344158",
    fontSize: 13,
    fontWeight: "700",
  },
  authInput: {
    minHeight: 48,
    backgroundColor: "#ffffff",
    fontSize: 15,
  },
  authPasswordField: {
    position: "relative",
  },
  authPasswordInput: {
    paddingRight: 72,
  },
  authPasswordToggle: {
    position: "absolute",
    right: 2,
    top: 2,
    minWidth: 60,
    minHeight: 44,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  authPasswordToggleText: {
    color: C.primaryDeep,
    fontSize: 13,
    fontWeight: "800",
  },
  authSubmitButton: {
    minHeight: 48,
    marginTop: 2,
  },
  noticeCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#d9e1ff",
    backgroundColor: "#eef3ff",
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  noticeText: {
    color: "#415590",
    fontSize: 13,
    lineHeight: 18,
  },
  mobileMenuRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  mobileMenuBtn: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#dde3ee",
    backgroundColor: "#ffffff",
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  mobileMenuBtnActive: {
    borderColor: C.primaryLight,
    backgroundColor: C.primaryGhost,
  },
  mobileMenuText: {
    color: "#3a465d",
    fontSize: 12,
    fontWeight: "700",
  },
  mobileMenuTextActive: {
    color: C.primaryDeep,
  },
} as const;
