import { marketingPalette as C } from "../../shared/design/palette";

export const adminModalStyles = {
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(17, 24, 39, 0.42)",
    alignItems: "center",
    justifyContent: "center",
    padding: 18,
  },
  modalCard: {
    width: "100%",
    maxWidth: 760,
    maxHeight: "90%",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#d8dee8",
    backgroundColor: "#ffffff",
    overflow: "hidden",
  },
  confirmCard: {
    width: "100%",
    maxWidth: 480,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#d8dee8",
    backgroundColor: "#ffffff",
    padding: 16,
    gap: 10,
  },
  productDeleteSummary: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e1e6ef",
    backgroundColor: "#f8fafc",
    padding: 12,
    gap: 5,
  },
  productDeleteCount: {
    color: "#2f3748",
    fontSize: 13,
    fontWeight: "800",
    marginBottom: 2,
  },
  productDeleteName: {
    color: "#4d5a70",
    fontSize: 13,
    lineHeight: 18,
  },
  confirmActionButton: {
    minHeight: 44,
  },
  modalHeader: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#e4e8f1",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
  },
  modalTitle: {
    color: "#2f3748",
    fontSize: 20,
    fontWeight: "800",
  },
  modalSub: {
    color: "#6c7890",
    fontSize: 12,
    lineHeight: 17,
    marginTop: 2,
  },
  modalBody: {
    maxHeight: 480,
  },
  modalBodyContent: {
    padding: 14,
    gap: 8,
  },
  modalTopGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  modalTopCell: {
    flexGrow: 1,
    minWidth: 260,
    gap: 7,
  },
  modalTopCellHalf: {
    flexBasis: "48%",
  },
  fieldLabel: {
    color: "#41506e",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 2,
  },
  choiceRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  choiceChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#d6deeb",
    backgroundColor: "#f7f9fc",
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  choiceChipActive: {
    borderColor: C.primaryLight,
    backgroundColor: C.primaryGhost,
  },
  choiceChipText: {
    color: "#40506c",
    fontSize: 12,
    fontWeight: "700",
  },
  choiceChipTextActive: {
    color: C.primaryDeep,
  },
  storePriceHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  storePriceGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  storePriceCard: {
    flexGrow: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#dbe2ef",
    backgroundColor: "#f8faff",
    padding: 10,
    gap: 10,
  },
  storePriceCardTwoCol: {
    minWidth: 260,
    flexBasis: "48%",
  },
  storePriceCardThreeCol: {
    minWidth: 220,
    flexBasis: "31.5%",
  },
  storePriceCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  storePriceCardTitle: {
    color: "#2f3748",
    fontSize: 13,
    fontWeight: "800",
  },
  storePriceFieldGroup: {
    gap: 6,
  },
  storeDropdownButton: {
    minHeight: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#d8dee8",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  storeDropdownTextWrap: {
    flex: 1,
    gap: 2,
  },
  storeDropdownSelectedText: {
    color: "#2f3748",
    fontSize: 13,
    fontWeight: "800",
  },
  storeDropdownPlaceholderText: {
    color: "#8a95ad",
    fontSize: 13,
    fontWeight: "700",
  },
  storeDropdownMetaText: {
    color: "#66748f",
    fontSize: 11,
    fontWeight: "600",
  },
  storeDropdownChevron: {
    color: C.primaryDeep,
    fontSize: 11,
    fontWeight: "800",
  },
  storeDropdownMenu: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#d8dee8",
    backgroundColor: "#ffffff",
    overflow: "hidden",
  },
  storeDropdownScroll: {
    maxHeight: 220,
  },
  storeDropdownOption: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderBottomWidth: 1,
    borderBottomColor: "#eef2f7",
    gap: 2,
  },
  storeDropdownOptionActive: {
    backgroundColor: C.primaryGhost,
  },
  storeDropdownOptionText: {
    color: "#2f3748",
    fontSize: 12,
    fontWeight: "800",
  },
  storeDropdownOptionTextActive: {
    color: C.primaryDeep,
  },
  storeDropdownOptionMeta: {
    color: "#66748f",
    fontSize: 11,
  },
  modalActionRow: {
    borderTopWidth: 1,
    borderTopColor: "#e4e8f1",
    padding: 12,
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
  },
  importStatusReady: {
    color: "#2c7a4b",
    fontSize: 12,
    fontWeight: "800",
    textAlign: "right",
  },
  importStatusMuted: {
    color: "#a05a2c",
    fontSize: 12,
    fontWeight: "800",
    textAlign: "right",
  },
} as const;
