import { marketingPalette as C } from "../../shared/design/palette";

export const adminModalStyles = {
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(17, 24, 39, 0.42)",
    alignItems: "center",
    justifyContent: "center",
    padding: 18,
  },
  modalCard: {
    width: "100%",
    maxWidth: 760,
    maxHeight: "90%",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#d8dee8",
    backgroundColor: "#ffffff",
    overflow: "hidden",
  },
  confirmCard: {
    width: "100%",
    maxWidth: 480,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#d8dee8",
    backgroundColor: "#ffffff",
    padding: 16,
    gap: 10,
  },
  modalHeader: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#e4e8f1",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
  },
  modalTitle: {
    color: "#2f3748",
    fontSize: 20,
    fontWeight: "800",
  },
  modalSub: {
    color: "#6c7890",
    fontSize: 12,
    lineHeight: 17,
    marginTop: 2,
  },
  modalBody: {
    maxHeight: 480,
  },
  modalBodyContent: {
    padding: 14,
    gap: 8,
  },
  modalTopGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  modalTopCell: {
    flexGrow: 1,
    minWidth: 260,
    gap: 7,
  },
  modalTopCellHalf: {
    flexBasis: "48%",
  },
  fieldLabel: {
    color: "#41506e",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 2,
  },
  choiceRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  choiceChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#d6deeb",
    backgroundColor: "#f7f9fc",
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  choiceChipActive: {
    borderColor: C.primaryLight,
    backgroundColor: C.primaryGhost,
  },
  choiceChipText: {
    color: "#40506c",
    fontSize: 12,
    fontWeight: "700",
  },
  choiceChipTextActive: {
    color: C.primaryDeep,
  },
  storePriceHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  storePriceGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  storePriceCard: {
    flexGrow: 1,
  },
  storePriceCardTwoCol: {
    minWidth: 260,
    flexBasis: "48%",
  },
  storePriceCardThreeCol: {
    minWidth: 220,
    flexBasis: "31.5%",
  },
  storePriceCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  storePriceCardTitle: {
    color: "#2f3748",
    fontSize: 13,
    fontWeight: "800",
  },
  modalActionRow: {
    borderTopWidth: 1,
    borderTopColor: "#e4e8f1",
    padding: 12,
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
  },
  importStatusReady: {
    color: "#2c7a4b",
    fontSize: 12,
    fontWeight: "800",
    textAlign: "right",
  },
  importStatusMuted: {
    color: "#a05a2c",
    fontSize: 12,
    fontWeight: "800",
    textAlign: "right",
  },
  modalImagePreview: {
    width: "100%",
    minHeight: 160,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#dbe1ec",
    backgroundColor: "#eef1f7",
  },
  imageUploadArea: {
    width: "100%",
    borderRadius: 12,
    overflow: "hidden",
    position: "relative",
  },
  imageUploadOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    minHeight: 34,
    backgroundColor: "rgba(24, 34, 52, 0.62)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  imageUploadOverlayText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "700",
  },
  modalImagePlaceholder: {
    alignItems: "center",
    justifyContent: "center",
  },
  storePillRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  storePill: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#dbe2ef",
    backgroundColor: "#f7f9fc",
    paddingHorizontal: 10,
    paddingVertical: 8,
    minWidth: 170,
    gap: 2,
  },
  storePillActive: {
    borderColor: C.primaryLight,
    backgroundColor: C.primaryGhost,
  },
  storePillText: {
    color: "#2f3748",
    fontSize: 12,
    fontWeight: "700",
  },
  storePillSubText: {
    color: "#66748f",
    fontSize: 11,
  },
  storePillTextActive: {
    color: C.primaryDeep,
  },
  dateBtn: {
    minWidth: 190,
    justifyContent: "flex-start",
  },
  dateBtnText: {
    color: "#3a4865",
    fontSize: 12,
    fontWeight: "700",
  },
  dateBtnPlaceholder: {
    color: "#8a95ad",
    fontSize: 12,
    fontWeight: "600",
  },
} as const;
