import { marketingPalette as C } from "../../shared/design/palette";

export const adminOverviewStyles = {
  statGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  overviewContent: {
    width: "100%",
    gap: 12,
  },
  productReviewCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e8b45c",
    backgroundColor: "#fff9eb",
    padding: 14,
    gap: 10,
  },
  productReviewCardError: {
    borderColor: "#d76b6b",
    backgroundColor: "#fff3f3",
  },
  productReviewCardReady: {
    borderColor: "#9bc9ae",
    backgroundColor: "#f2fbf5",
  },
  productReviewHeading: {
    flex: 1,
    minWidth: 240,
    gap: 3,
  },
  productReviewTitle: {
    color: "#764b00",
    fontSize: 16,
    fontWeight: "800",
  },
  productReviewTitleError: {
    color: "#a52828",
  },
  productReviewTitleReady: {
    color: "#176b3a",
  },
  productReviewDescription: {
    color: "#8a6728",
    fontSize: 12,
    lineHeight: 17,
  },
  productReviewDescriptionError: {
    color: "#8e3030",
  },
  productReviewDescriptionReady: {
    color: "#3a7752",
  },
  productReviewList: {
    gap: 7,
  },
  productReviewRow: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ead5aa",
    backgroundColor: "#ffffff",
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 10,
  },
  productReviewReason: {
    color: "#895b0a",
    fontSize: 11,
    fontWeight: "700",
  },
  productReviewActions: {
    alignItems: "flex-end",
    gap: 5,
  },
  statCard: {
    minWidth: 140,
    flexGrow: 1,
    borderRadius: 12,
    borderWidth: 0,
    backgroundColor: "#f8faff",
    paddingHorizontal: 10,
    paddingVertical: 7,
    gap: 1,
  },
  statLabel: {
    color: "#748096",
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  statValue: {
    color: "#2b313d",
    fontSize: 22,
    lineHeight: 24,
    fontWeight: "800",
  },
  statHint: {
    color: "#6f7b8f",
    fontSize: 10,
    lineHeight: 12,
  },
  dataHealthCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#cfdcd7",
    backgroundColor: "#ffffff",
    padding: 14,
    gap: 12,
  },
  dataHealthHeading: {
    flex: 1,
    minWidth: 260,
    gap: 3,
  },
  dataHealthProgressHeader: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 8,
    flexWrap: "wrap",
  },
  dataHealthProgressValue: {
    color: C.primaryDeep,
    fontSize: 24,
    fontWeight: "900",
  },
  dataHealthProgressTrack: {
    height: 9,
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: "#e9efec",
  },
  dataHealthProgressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: C.primary,
  },
  dataHealthMetricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  dataHealthMetric: {
    minWidth: 124,
    flexGrow: 1,
    borderRadius: 10,
    backgroundColor: "#f5f8f7",
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 2,
  },
  dataHealthMetricValue: {
    color: "#2b313d",
    fontSize: 19,
    fontWeight: "900",
  },
  dataHealthMetricLabel: {
    color: "#6f7b8f",
    fontSize: 10,
    fontWeight: "700",
  },
  dataHealthIssueRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
  },
  dataHealthIssueText: {
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: "#fff5e5",
    color: "#805513",
    paddingHorizontal: 9,
    paddingVertical: 5,
    fontSize: 10,
    fontWeight: "800",
  },
  dataHealthIssueChip: {
    borderRadius: 999,
    backgroundColor: "#fff5e5",
    paddingHorizontal: 9,
    paddingVertical: 5,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  dataHealthReadyChip: {
    backgroundColor: "#edf9f2",
  },
  dataHealthIssueLabel: {
    color: "#805513",
    fontSize: 10,
    fontWeight: "800",
  },
  dataHealthReadyText: {
    color: "#16824b",
  },
  dataHealthQueueHeader: {
    borderTopWidth: 1,
    borderTopColor: "#e4ebe8",
    paddingTop: 11,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 10,
    flexWrap: "wrap",
  },
  dataHealthQueue: {
    gap: 7,
  },
  dataHealthQueueRow: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#dce5e1",
    backgroundColor: "#fbfcfc",
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    flexWrap: "wrap",
  },
  dataHealthQueueStatus: {
    alignItems: "flex-end",
    gap: 3,
  },
  dataHealthSessionBadge: {
    color: C.primaryDeep,
    fontSize: 11,
    fontWeight: "900",
  },
  dataHealthIdentityWarning: {
    color: "#985f16",
    fontSize: 10,
    fontWeight: "700",
  },
  panelTitle: {
    color: "#2d3444",
    fontSize: 28,
    fontWeight: "800",
    marginTop: 2,
  },
  recentProductGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  recentProductRow: {
    minWidth: 280,
    flexBasis: "48%",
    flexGrow: 1,
  },
  productAdminStack: {
    gap: 12,
  },
} as const;
