import { Platform } from "react-native";
import { marketingPalette as C } from "../../shared/design/palette";

export const adminProductListStyles: Record<string, any> = {
  productHeaderStack: {
    position: "relative",
    zIndex: 20,
    gap: 8,
  },
  csvActionsMenuPanelInline: {
    width: "100%",
    maxWidth: 280,
    alignSelf: "flex-end",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#d8dee8",
    backgroundColor: "#ffffff",
    padding: 6,
    gap: 2,
    ...(Platform.OS === "web"
      ? ({
          position: "absolute",
          top: "100%",
          right: 0,
          zIndex: 30,
          marginTop: 8,
          boxShadow: "0 10px 24px rgba(36, 48, 72, 0.12)",
        } as any)
      : {}),
  },
  productListTable: {
    width: "100%",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#dce3ed",
    backgroundColor: "#ffffff",
    overflow: "hidden",
  },
  productListColumnHeader: {
    minHeight: 42,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#f3f6fa",
  },
  productListColumnLabel: {
    color: "#6f7b8e",
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.35,
  },
  productListSelectColumn: {
    width: 32,
    minWidth: 32,
  },
  productListProductColumn: {
    flex: 1,
    minWidth: 0,
  },
  productListLatestColumn: {
    width: 74,
    minWidth: 74,
    justifyContent: "center",
  },
  productListHistoryColumn: {
    width: 64,
    minWidth: 64,
    justifyContent: "center",
  },
  productListSaleColumn: {
    width: 240,
    minWidth: 240,
    justifyContent: "center",
    gap: 3,
  },
  productListActionsColumn: {
    width: 204,
    minWidth: 204,
    justifyContent: "center",
  },
  productListRow: {
    minWidth: 0,
    borderTopWidth: 1,
    borderTopColor: "#e7ebf1",
    backgroundColor: "#ffffff",
  },
  productListRowSelected: {
    backgroundColor: C.primaryGhost,
  },
  productListRowMain: {
    minWidth: 0,
    paddingHorizontal: 12,
    paddingVertical: 11,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  productListRowMainCompact: {
    flexWrap: "wrap",
    alignItems: "flex-start",
    gap: 10,
  },
  productListProductCell: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  productListProductCellCompact: {
    minWidth: 210,
  },
  productListThumbnail: {
    width: 52,
    height: 52,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: "#dce4ef",
    backgroundColor: "#eef2f8",
  },
  productListThumbnailPlaceholder: {
    width: 52,
    height: 52,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: "#dce4ef",
    backgroundColor: "#eef8f3",
    alignItems: "center",
    justifyContent: "center",
  },
  productListIdentity: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  productListTitle: {
    color: "#2f3748",
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "800",
  },
  productListSubtitle: {
    color: "#647188",
    fontSize: 11,
    lineHeight: 15,
  },
  productListCategory: {
    color: "#506078",
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "700",
  },
  productListCreated: {
    color: "#8a94a5",
    fontSize: 9,
    lineHeight: 13,
    fontWeight: "700",
  },
  productListMetricLabel: {
    color: "#7b8799",
    fontSize: 9,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  productListMetricValue: {
    color: "#33425e",
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
  },
  productListMetricSecondary: {
    color: "#6f7b8e",
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "600",
  },
  productListCompactMetrics: {
    width: "100%",
    flexDirection: "row",
    gap: 7,
  },
  productListCompactMetric: {
    flex: 0.8,
    minWidth: 70,
    borderRadius: 8,
    backgroundColor: "#f3f6fa",
    paddingHorizontal: 9,
    paddingVertical: 7,
    gap: 2,
  },
  productListCompactSale: {
    width: "100%",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e3e8f1",
    paddingHorizontal: 9,
    paddingVertical: 7,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  productListSaleGroup: {
    flex: 1,
    minWidth: 180,
    gap: 2,
  },
  productListSaleValue: {
    color: "#46536a",
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "700",
  },
  productListActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
  },
  productListActionsCompact: {
    width: "100%",
    flexWrap: "wrap",
  },
  productListActionButton: {
    minHeight: 34,
    minWidth: 64,
    paddingHorizontal: 9,
  },
  productListDetailsButtonActive: {
    borderColor: C.primaryLight,
    backgroundColor: C.primaryGhost,
  },
  productListDetailsPanel: {
    borderTopWidth: 1,
    borderTopColor: "#e7ebf1",
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#fafbfd",
  },
};
