import { Platform } from "react-native";
import { marketingPalette as C } from "../../shared/design/palette";

export const adminSidebarStyles = {
  sidebar: {
    width: 280,
    minHeight: 0,
    height: "100%",
    borderRadius: 0,
    borderWidth: 1,
    borderColor: "#d8dee8",
    backgroundColor: "#ffffff",
    padding: 14,
    gap: 14,
    ...(Platform.OS === "web" ? ({ height: "100vh", alignSelf: "stretch" } as any) : {}),
  },
  sidebarMobile: {
    width: "100%",
    minHeight: 0,
    height: "auto",
    borderRadius: 12,
    position: "relative",
    padding: 8,
    gap: 8,
    flexDirection: "row",
    alignItems: "center",
  },
  sidebarHeader: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#dde3ee",
    backgroundColor: "#f5f8ff",
    padding: 12,
    gap: 4,
  },
  sidebarHeaderMobile: {
    flex: 0.9,
    minWidth: 100,
    borderWidth: 0,
    backgroundColor: "transparent",
    padding: 0,
    gap: 0,
  },
  sidebarBrand: {
    color: "#2a3f7f",
    fontSize: 18,
    fontWeight: "800",
  },
  sidebarSub: {
    color: "#5d6a82",
    fontSize: 12,
    lineHeight: 17,
  },
  menuGroup: {
    gap: 8,
  },
  menuBtn: {
    minHeight: 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#dfe4ec",
    backgroundColor: "#ffffff",
    paddingHorizontal: 11,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  menuBtnActive: {
    borderColor: C.primaryLight,
    backgroundColor: C.primaryGhost,
  },
  menuText: {
    color: "#2e3a4f",
    fontSize: 13,
    fontWeight: "700",
  },
  menuTextActive: {
    color: C.primaryDeep,
  },
  menuBadge: {
    minWidth: 24,
    height: 24,
    borderRadius: 999,
    backgroundColor: "#eceff4",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  menuBadgeActive: {
    backgroundColor: C.primaryPale,
  },
  menuBadgeText: {
    color: "#4e5c74",
    fontSize: 11,
    fontWeight: "800",
  },
  menuBadgeTextActive: {
    color: C.primaryDeep,
  },
  sidebarReviewAlert: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e9b65f",
    backgroundColor: "#fff8e8",
    paddingHorizontal: 11,
    paddingVertical: 9,
    gap: 2,
    marginTop: -3,
  },
  sidebarReviewAlertTitle: {
    color: "#815400",
    fontSize: 12,
    fontWeight: "800",
  },
  sidebarReviewAlertBody: {
    color: "#906d2c",
    fontSize: 10,
    lineHeight: 14,
  },
  sidebarFooter: {
    marginTop: "auto",
    borderTopWidth: 1,
    borderTopColor: "#e5e9f1",
    paddingTop: 12,
    gap: 7,
  },
  sidebarFooterMobile: {
    flex: 0,
    minWidth: 0,
    marginTop: 0,
    borderTopWidth: 0,
    paddingTop: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
  },
  sidebarUserBlock: {
    flex: 1,
    minWidth: 0,
  },
  sidebarUser: {
    color: "#2e3748",
    fontSize: 13,
    fontWeight: "700",
  },
  sidebarRole: {
    color: "#7a859a",
    fontSize: 12,
  },
  sidebarCollapsedToggle: {
    width: 54,
    height: 54,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#cfd7ea",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    ...(Platform.OS === "web"
      ? ({ position: "fixed", left: 12, bottom: 12, zIndex: 40, boxShadow: "0 8px 20px rgba(24,34,52,0.18)" } as any)
      : ({ position: "absolute", left: 12, bottom: 12 } as any)),
  },
  sidebarCollapsedToggleIcon: {
    color: C.primaryDeep,
    fontSize: 28,
    fontWeight: "900",
    marginTop: -2,
  },
} as const;
