export const adminUserStyles: Record<string, any> = {
  userDirectoryStack: {
    gap: 12,
  },
  userDirectoryIntro: {
    color: "#68758a",
    fontSize: 13,
    lineHeight: 19,
  },
  userDirectorySearch: {
    flexGrow: 1,
    minWidth: 320,
  },
  userDirectoryLoading: {
    minHeight: 160,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  userDirectoryList: {
    width: "100%",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#dce3ed",
    backgroundColor: "#ffffff",
    overflow: "hidden",
  },
  userDirectoryColumnHeader: {
    minHeight: 42,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#f3f6fa",
  },
  userDirectoryColumnLabel: {
    color: "#6f7b8e",
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.35,
  },
  userDirectoryRow: {
    minWidth: 0,
    borderTopWidth: 1,
    borderTopColor: "#e7ebf1",
    backgroundColor: "#ffffff",
  },
  userDirectoryRowMain: {
    minWidth: 0,
    paddingHorizontal: 12,
    paddingVertical: 11,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  userDirectoryRowMainCompact: {
    flexWrap: "wrap",
    alignItems: "stretch",
    gap: 8,
  },
  userDirectoryUserColumn: {
    flex: 1,
    minWidth: 0,
    gap: 7,
  },
  userDirectoryAccountColumn: {
    width: 184,
    minWidth: 184,
    gap: 7,
  },
  userDirectoryProfileColumn: {
    width: 142,
    minWidth: 142,
    gap: 7,
  },
  userDirectoryActivityColumn: {
    width: 224,
    minWidth: 224,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 5,
  },
  userDirectoryActionsColumn: {
    width: 78,
    minWidth: 78,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  userDirectoryColumnCompact: {
    width: "100%",
    minWidth: "100%",
  },
  userDirectoryCompactMetric: {
    flex: 1,
    width: "auto",
    minWidth: 190,
    borderRadius: 8,
    backgroundColor: "#f3f6fa",
    paddingHorizontal: 9,
    paddingVertical: 7,
  },
  userDirectoryActivityColumnCompact: {
    width: "100%",
    minWidth: "100%",
  },
  userDirectoryActionsColumnCompact: {
    width: "100%",
    minWidth: "100%",
  },
  userDirectoryIdentityHeader: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  userDirectoryIdentity: {
    flexGrow: 1,
    minWidth: 180,
    gap: 2,
  },
  userDirectoryName: {
    color: "#2d3444",
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "800",
  },
  userDirectoryEmail: {
    color: "#66748a",
    fontSize: 12,
    lineHeight: 17,
  },
  userDirectoryStatusRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 5,
  },
  userDirectoryStatusChip: {
    borderRadius: 999,
    backgroundColor: "#edf1f6",
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  userDirectoryStatusChipAdmin: {
    backgroundColor: "#e5e7ff",
  },
  userDirectoryStatusChipSuccess: {
    backgroundColor: "#dcf5e7",
  },
  userDirectoryStatusChipWarning: {
    backgroundColor: "#fff0d6",
  },
  userDirectoryStatusText: {
    color: "#3f4b5e",
    fontSize: 10,
    fontWeight: "800",
  },
  userDirectoryLabelValue: {
    gap: 1,
  },
  userDirectoryMetaLabel: {
    color: "#8490a2",
    fontSize: 9,
    lineHeight: 13,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  userDirectoryMetaValue: {
    color: "#394457",
    fontSize: 12,
    lineHeight: 17,
  },
  userDirectoryPreferencesInline: {
    gap: 2,
  },
  userDirectoryPreferenceText: {
    color: "#5b687d",
    fontSize: 10,
    lineHeight: 14,
  },
  userDirectoryPreferenceLabel: {
    color: "#778397",
    fontWeight: "800",
  },
  userDirectoryActivityText: {
    borderRadius: 7,
    backgroundColor: "#f2f5f9",
    color: "#4d5a6f",
    paddingHorizontal: 7,
    paddingVertical: 5,
    fontSize: 10,
    fontWeight: "700",
  },
  userDirectoryDetailsButton: {
    minWidth: 70,
    minHeight: 34,
    paddingHorizontal: 9,
  },
  userDirectoryDetailsButtonActive: {
    borderColor: "#9bcfb2",
    backgroundColor: "#edf9f2",
  },
  userDirectoryDetailsPanel: {
    borderTopWidth: 1,
    borderTopColor: "#edf0f5",
    backgroundColor: "#fafbfd",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
};
