export const PRODUCT_IMPORT_HEADERS = {
  productId: ["product_id", "productid", "product id", "id", "상품id", "상품_id"],
  koreanName: ["korean_name", "koreanname", "korean name", "name", "product_name", "product", "이름", "상품명", "제품명"],
  englishName: ["english_name", "englishname", "english name", "eng_name", "eng name", "영문명", "영문이름", "영문 이름"],
  productBrand: ["product_brand", "product brand", "brand", "manufacturer", "제조사", "상품브랜드", "상품 브랜드"],
  gtin: ["gtin", "upc", "ean", "barcode", "bar_code", "바코드"],
  category: ["category", "main_category", "대분류", "카테고리", "분류"],
  unit: ["unit", "size", "size_unit", "용량", "규격"],
  thumbnailUrl: ["thumbnail_url", "thumbnail", "image_url", "image", "이미지", "이미지url"],
  storeId: ["store_id", "storeid", "store id"],
  storeName: ["store_name", "store", "stores", "summary_stores", "store name", "매장", "마트"],
  storeBrand: ["store_brand", "store brand", "summary_store_brands", "mart_brand", "mart brand", "마트브랜드"],
  storeAddress: ["store_address", "address", "store address", "주소"],
  storePlaceId: ["store_place_id", "place_id", "placeid", "google_place_id", "google_place", "장소id"],
  storeLatitude: ["store_latitude", "latitude", "lat", "위도"],
  storeLongitude: ["store_longitude", "longitude", "lng", "lon", "경도"],
  price: ["price", "current_price", "latest_price", "summary_latest_price", "source_price", "price_value", "가격"],
  observedAt: ["observed_at", "observedat", "valid_from", "sale_start_date", "summary_sale_start_date", "date", "날짜", "시작일", "시작 날짜", "기준일"],
  periodEnd: ["valid_to", "period_end", "sale_end_date", "summary_sale_end_date", "valid to", "종료일", "종료 날짜"],
};
